/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_BaoHanh;

import QuanLiXeMay.DanhSachXeMay;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import QuanLyBaoHanh.HeThongBaoHanh;
import QuanLyBaoHanh.DanhSachBaoHanh;
import QuanLiLinhKien.LinhKien;
import QuanLiLinhKien.DanhSachLinhKien;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import javax.swing.table.TableModel;

/**
 *
 * @author Tuan Dat
 */
public class GUI_BaoHanh extends javax.swing.JFrame {

    private DanhSachBaoHanh ds_BaoHanh;
    private DanhSachBaoHanh ds_TimKiemMaXe_BH;
    
    private DanhSachLinhKien ds_LinhKien;

    /* Creates new form GUI_QuanLi
     */
    public GUI_BaoHanh() throws ClassNotFoundException, SQLException {
        super("Quản lí cửa hàng xe máy");
        initComponents();
        setResizable(true);
        ds_LinhKien = new DanhSachLinhKien();
        ds_BaoHanh = new DanhSachBaoHanh();
        ds_BaoHanh.layDuLieu();
        ds_LinhKien.layDuLieu();
        loadDataLinhKien();
        loadDataBaoHanh();

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //setLocationRelativeTo(null);
        setLocation(0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_ChiTietKhachHang = new javax.swing.JPanel();
        lbl_MaKhachHang = new javax.swing.JLabel();
        lbl_HoKhachHang = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        lbl_TenKhachHang = new javax.swing.JLabel();
        lbl_DiaChiKhachHang = new javax.swing.JLabel();
        lbl_SoDienThoai = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        btn_Them_KhachHang = new javax.swing.JButton();
        btn_Xoa_KhachHang = new javax.swing.JButton();
        btn_CapNhat_KhachHang = new javax.swing.JButton();
        btn_PhatSinh_MaKhachHang = new javax.swing.JButton();
        btn_XoaTrang_KhachHang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_SoChungMinh = new javax.swing.JLabel();
        txt_SoChungMinh = new javax.swing.JTextField();
        pn_XeMay_KhachHang = new javax.swing.JTabbedPane();
        pn_Baohanh = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_TenKhachHang_BH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_MaXe_BH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_LyDo_BH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_LinhKien_BH = new javax.swing.JTextField();
        txt_GiaTien_BH = new javax.swing.JTextField();
        txt_NhanVien_BH = new javax.swing.JTextField();
        txt_DiaChi_BH = new javax.swing.JTextField();
        cbx_Loi_BaoHanh = new javax.swing.JComboBox<>();
        txt_MaBaoHanh_BH = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_PhatSinhMaBH = new javax.swing.JButton();
        btn_Them_BH = new javax.swing.JButton();
        btn_Xoa_BH = new javax.swing.JButton();
        btn_CapNhat_BH = new javax.swing.JButton();
        btn_XoaTrang_BH = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        myTable_BaoHanh = new javax.swing.JTable();
        btn_TimKiem_BH = new javax.swing.JButton();
        btn_InPhieu_BH = new javax.swing.JButton();
        btn_Huy_BH = new javax.swing.JButton();
        txt_TimKiem_BH = new javax.swing.JTextField();
        lbl_TimKiem_BH = new javax.swing.JLabel();
        lbl_TimLinhKien_LK = new javax.swing.JLabel();
        txt_TimKiem_LK = new javax.swing.JTextField();
        btn_TimKiem_LK = new javax.swing.JButton();
        btn_Huy_LK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable_LinhKien = new javax.swing.JTable();
        lbl_TenLinhKien_LK = new javax.swing.JLabel();
        lbl_GiaTien_LK = new javax.swing.JLabel();
        txt_Ten_LK = new javax.swing.JTextField();
        txt_GiaTien_LK = new javax.swing.JTextField();
        btn_ThemLK = new javax.swing.JButton();
        bnt_Xoa_LK = new javax.swing.JButton();
        btn_CapNhat_LK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pn_ChiTietKhachHang.setPreferredSize(new java.awt.Dimension(982, 535));

        lbl_MaKhachHang.setText("Mã khách hàng");

        lbl_HoKhachHang.setText("Họ");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thông tin chi tiết khách hàng");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ", "Tên", "Địa chỉ", "Số điện thoại"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton6.setText("Tìm ");

        lbl_TenKhachHang.setText("Tên");

        lbl_DiaChiKhachHang.setText("Địa chỉ");

        lbl_SoDienThoai.setText("Số điện thoại");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        btn_Them_KhachHang.setText("Thêm");

        btn_Xoa_KhachHang.setText("Xóa");

        btn_CapNhat_KhachHang.setText("Cập nhật");

        btn_PhatSinh_MaKhachHang.setText("Phát sinh mã khách hàng");

        btn_XoaTrang_KhachHang.setText("Xóa trắng");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số khách hàng hiện tại : ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("0");

        lbl_SoChungMinh.setText("Số chứng minh");

        javax.swing.GroupLayout pn_ChiTietKhachHangLayout = new javax.swing.GroupLayout(pn_ChiTietKhachHang);
        pn_ChiTietKhachHang.setLayout(pn_ChiTietKhachHangLayout);
        pn_ChiTietKhachHangLayout.setHorizontalGroup(
            pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ChiTietKhachHangLayout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_HoKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbl_TenKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_DiaChiKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_SoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                                .addComponent(btn_Them_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                                        .addGap(39, 39, 39)
                                                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btn_CapNhat_KhachHang)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btn_Xoa_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(btn_PhatSinh_MaKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                            .addComponent(btn_XoaTrang_KhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                                        .addComponent(lbl_SoChungMinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_SoChungMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        pn_ChiTietKhachHangLayout.setVerticalGroup(
            pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_MaKhachHang)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(829, Short.MAX_VALUE))
                    .addGroup(pn_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_HoKhachHang)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TenKhachHang)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DiaChiKhachHang)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SoDienThoai)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SoChungMinh)
                            .addComponent(txt_SoChungMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_PhatSinh_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them_KhachHang)
                            .addComponent(btn_Xoa_KhachHang)
                            .addComponent(btn_CapNhat_KhachHang))
                        .addGap(18, 18, 18)
                        .addComponent(btn_XoaTrang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_Baohanh.setPreferredSize(new java.awt.Dimension(1006, 460));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("Mã bảo hành");

        jLabel5.setText("Tên khách hàng");

        txt_TenKhachHang_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenKhachHang_BHActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã xe");

        txt_MaXe_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaXe_BHActionPerformed(evt);
            }
        });

        jLabel7.setText("Lí do");

        jLabel8.setText("Lỗi thuộc về");

        jLabel9.setText("Linh kiện");

        jLabel10.setText("Giá tiền");

        jLabel12.setText("Nhân viên thực hiện");

        jLabel13.setText("Địa chỉ");

        txt_LinhKien_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LinhKien_BHActionPerformed(evt);
            }
        });

        txt_NhanVien_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhanVien_BHActionPerformed(evt);
            }
        });

        txt_DiaChi_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiaChi_BHActionPerformed(evt);
            }
        });

        cbx_Loi_BaoHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng", "Sản phầm" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TenKhachHang_BH)
                    .addComponent(txt_MaXe_BH)
                    .addComponent(txt_LyDo_BH)
                    .addComponent(txt_LinhKien_BH)
                    .addComponent(txt_GiaTien_BH)
                    .addComponent(txt_NhanVien_BH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbx_Loi_BaoHanh, 0, 209, Short.MAX_VALUE)
                    .addComponent(txt_MaBaoHanh_BH)
                    .addComponent(txt_DiaChi_BH))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_MaBaoHanh_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TenKhachHang_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_MaXe_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_LyDo_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbx_Loi_BaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_LinhKien_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_GiaTien_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_NhanVien_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DiaChi_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_PhatSinhMaBH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:create.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_PhatSinhMaBH.setText("Phát sinh mã bảo hành");
        btn_PhatSinhMaBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhatSinhMaBHActionPerformed(evt);
            }
        });

        btn_Them_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:add.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Them_BH.setText("Thêm");
        btn_Them_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them_BHActionPerformed(evt);
            }
        });

        btn_Xoa_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:remove.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Xoa_BH.setText("Xóa");
        btn_Xoa_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa_BHActionPerformed(evt);
            }
        });

        btn_CapNhat_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:update.PNG")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_CapNhat_BH.setText("Cập nhật");
        btn_CapNhat_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhat_BHActionPerformed(evt);
            }
        });

        btn_XoaTrang_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:arrow_refresh.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_XoaTrang_BH.setText("Làm mới");
        btn_XoaTrang_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTrang_BHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_PhatSinhMaBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Them_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Xoa_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_CapNhat_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_XoaTrang_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_PhatSinhMaBH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_XoaTrang_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhat_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        myTable_BaoHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã BH", "Tên KH", "Mã xe", "Lý do", "Lỗi", "Linh kiện", "G.tiền (nghìn)", "Nhân viên BH", "Đc đại lý"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable_BaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTable_BaoHanhMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(myTable_BaoHanh);

        btn_TimKiem_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:search.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_TimKiem_BH.setText("Tìm kiếm");
        btn_TimKiem_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_BHActionPerformed(evt);
            }
        });

        btn_InPhieu_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:print.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_InPhieu_BH.setText("In phiếu");
        btn_InPhieu_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InPhieu_BHActionPerformed(evt);
            }
        });

        btn_Huy_BH.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Huy_BH.setText("Hủy");
        btn_Huy_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_BHActionPerformed(evt);
            }
        });

        txt_TimKiem_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiem_BHActionPerformed(evt);
            }
        });

        lbl_TimKiem_BH.setText("Nhập mã BH, mã xe để tìm :");

        lbl_TimLinhKien_LK.setText("Nhập tên linh kiện để tìm kiếm");

        btn_TimKiem_LK.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:search.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_TimKiem_LK.setText("Tìm Kiếm");
        btn_TimKiem_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_LKActionPerformed(evt);
            }
        });

        btn_Huy_LK.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Huy_LK.setText("Hủy");
        btn_Huy_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_LKActionPerformed(evt);
            }
        });

        myTable_LinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên linh kiện", "Giá tiền( Nghìn đồng)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable_LinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTable_LinhKienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myTable_LinhKien);

        lbl_TenLinhKien_LK.setText("Tên linh kiện");

        lbl_GiaTien_LK.setText("Giá tiền");

        txt_Ten_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Ten_LKActionPerformed(evt);
            }
        });

        txt_GiaTien_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaTien_LKActionPerformed(evt);
            }
        });

        btn_ThemLK.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:add.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_ThemLK.setText("Thêm");
        btn_ThemLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLKActionPerformed(evt);
            }
        });

        bnt_Xoa_LK.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:remove.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        bnt_Xoa_LK.setText("Xóa");
        bnt_Xoa_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_Xoa_LKActionPerformed(evt);
            }
        });

        btn_CapNhat_LK.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:update.PNG")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_CapNhat_LK.setText("Cập nhật");
        btn_CapNhat_LK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhat_LKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_TimKiem_BH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(txt_TimKiem_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_TimKiem_BH)
                        .addGap(11, 11, 11)
                        .addComponent(btn_Huy_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_InPhieu_BH))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_TimLinhKien_LK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TimKiem_LK, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_TimKiem_LK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Huy_LK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnt_Xoa_LK))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_TenLinhKien_LK)
                        .addGap(40, 40, 40)
                        .addComponent(txt_Ten_LK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_GiaTien_LK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_GiaTien_LK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_CapNhat_LK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_TimKiem_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_InPhieu_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_TimKiem_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Huy_BH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TimKiem_BH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_TimKiem_LK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Huy_LK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_TimLinhKien_LK)
                        .addComponent(bnt_Xoa_LK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_TimKiem_LK))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenLinhKien_LK)
                    .addComponent(txt_Ten_LK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhat_LK))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GiaTien_LK)
                    .addComponent(txt_GiaTien_LK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemLK))
                .addGap(28, 28, 28))
        );

        jLabel1.setBackground(new java.awt.Color(51, 51, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hệ thống bảo hành");

        javax.swing.GroupLayout pn_BaohanhLayout = new javax.swing.GroupLayout(pn_Baohanh);
        pn_Baohanh.setLayout(pn_BaohanhLayout);
        pn_BaohanhLayout.setHorizontalGroup(
            pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BaohanhLayout.createSequentialGroup()
                .addGroup(pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_BaohanhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_BaohanhLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_BaohanhLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pn_BaohanhLayout.setVerticalGroup(
            pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BaohanhLayout.createSequentialGroup()
                .addGroup(pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addGroup(pn_BaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_BaohanhLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_XeMay_KhachHang.addTab("Bảo Hành", pn_Baohanh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_XeMay_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_XeMay_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void btn_Huy_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_BHActionPerformed
        // TODO add your handling code here:
        try {

            DefaultTableModel tableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
            tableModel.setRowCount(0);

            ds_BaoHanh = new DanhSachBaoHanh();
            ds_BaoHanh.layDuLieu();
            loadDataBaoHanh();
            xoaTrangBH();
            btn_Them_BH.setEnabled(true);
            btn_PhatSinhMaBH.setEnabled(true);
            txt_TenKhachHang_BH.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_Huy_BHActionPerformed

    private void btn_PhatSinhMaBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhatSinhMaBHActionPerformed
        // TODO add your handling code here:
        txt_MaBaoHanh_BH.setText(Integer.toString(phatSinhMBH()));
    }//GEN-LAST:event_btn_PhatSinhMaBHActionPerformed

    private void btn_InPhieu_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InPhieu_BHActionPerformed
        try {
            // TODO add your handling code here:
            inPhieuBaoHanh();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_InPhieu_BHActionPerformed

    private void txt_TimKiem_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiem_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiem_BHActionPerformed

    private void myTable_BaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTable_BaoHanhMouseClicked
        // TODO add your handling code here:
        int row = myTable_BaoHanh.getSelectedRow();
        txt_MaBaoHanh_BH.setText(myTable_BaoHanh.getValueAt(row, 0).toString());
        txt_TenKhachHang_BH.setText(myTable_BaoHanh.getValueAt(row, 1).toString());
        txt_MaXe_BH.setText(myTable_BaoHanh.getValueAt(row, 2).toString());
        txt_LyDo_BH.setText(myTable_BaoHanh.getValueAt(row, 3).toString());
        String loi = myTable_BaoHanh.getValueAt(row, 4).toString();
        if (loi.equalsIgnoreCase("Khách hàng")) {
            cbx_Loi_BaoHanh.setSelectedIndex(0);
        } else {
            cbx_Loi_BaoHanh.setSelectedIndex(1);
        }
        txt_LinhKien_BH.setText(myTable_BaoHanh.getValueAt(row, 5).toString());
        txt_GiaTien_BH.setText(myTable_BaoHanh.getValueAt(row, 6).toString());
        txt_NhanVien_BH.setText(myTable_BaoHanh.getValueAt(row, 7).toString());
        txt_DiaChi_BH.setText(myTable_BaoHanh.getValueAt(row, 8).toString());
        btn_PhatSinhMaBH.setEnabled(false);
        btn_Them_BH.setEnabled(false);
    }//GEN-LAST:event_myTable_BaoHanhMouseClicked

    private void btn_XoaTrang_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTrang_BHActionPerformed
        xoaTrangBH();
    }//GEN-LAST:event_btn_XoaTrang_BHActionPerformed

    private void btn_TimKiem_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_BHActionPerformed
        // TODO add your handling code here:
        timKiemBaoHanh();
    }//GEN-LAST:event_btn_TimKiem_BHActionPerformed

    private void btn_CapNhat_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhat_BHActionPerformed
        // TODO add your handling code here:
        capNhatBaoHanh();
    }//GEN-LAST:event_btn_CapNhat_BHActionPerformed

    private void btn_Xoa_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa_BHActionPerformed
        try {
            // TODO add your handling code here:
            xoaBaoHanh();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Xoa_BHActionPerformed

    private void btn_Them_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them_BHActionPerformed
        try {
            // TODO add your handling code here:
//            JOptionPane.showMessageDialog(this, "blabla");
            themBH();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Them_BHActionPerformed

    private void txt_TenKhachHang_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenKhachHang_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenKhachHang_BHActionPerformed

    private void txt_NhanVien_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhanVien_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NhanVien_BHActionPerformed

    private void txt_LinhKien_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LinhKien_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LinhKien_BHActionPerformed

    private void txt_DiaChi_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiaChi_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DiaChi_BHActionPerformed

    private void txt_MaXe_BHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaXe_BHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaXe_BHActionPerformed

    private void btn_ThemLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLKActionPerformed
        try {
            // TODO add your handling code here:

            themLK_LK();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_ThemLKActionPerformed

    private void myTable_LinhKienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTable_LinhKienMouseClicked
        // TODO add your handling code here:
        int row = myTable_LinhKien.getSelectedRow();
        if(row != -1)
            txt_Ten_LK.setEnabled(false);
        txt_Ten_LK.setText(myTable_LinhKien.getValueAt(row, 0).toString());
        txt_GiaTien_LK.setText(myTable_LinhKien.getValueAt(row, 1).toString());
    }//GEN-LAST:event_myTable_LinhKienMouseClicked

    private void txt_GiaTien_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaTien_LKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaTien_LKActionPerformed

    private void txt_Ten_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Ten_LKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Ten_LKActionPerformed

    private void bnt_Xoa_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_Xoa_LKActionPerformed
        // TODO add your handling code here:
        xoaLinhKien();
    }//GEN-LAST:event_bnt_Xoa_LKActionPerformed

    private void btn_TimKiem_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_LKActionPerformed
        // TODO add your handling code here:
        timKiemLK();
    }//GEN-LAST:event_btn_TimKiem_LKActionPerformed

    private void btn_Huy_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_LKActionPerformed
        try {
            // TODO add your handling code here:
            huyLK();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_BaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Huy_LKActionPerformed

    private void btn_CapNhat_LKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhat_LKActionPerformed
        // TODO add your handling code here:
        capNhatLK();
    }//GEN-LAST:event_btn_CapNhat_LKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Xoa_LK;
    private javax.swing.JButton btn_CapNhat_BH;
    private javax.swing.JButton btn_CapNhat_KhachHang;
    private javax.swing.JButton btn_CapNhat_LK;
    private javax.swing.JButton btn_Huy_BH;
    private javax.swing.JButton btn_Huy_LK;
    private javax.swing.JButton btn_InPhieu_BH;
    private javax.swing.JButton btn_PhatSinhMaBH;
    private javax.swing.JButton btn_PhatSinh_MaKhachHang;
    private javax.swing.JButton btn_ThemLK;
    private javax.swing.JButton btn_Them_BH;
    private javax.swing.JButton btn_Them_KhachHang;
    private javax.swing.JButton btn_TimKiem_BH;
    private javax.swing.JButton btn_TimKiem_LK;
    private javax.swing.JButton btn_XoaTrang_BH;
    private javax.swing.JButton btn_XoaTrang_KhachHang;
    private javax.swing.JButton btn_Xoa_BH;
    private javax.swing.JButton btn_Xoa_KhachHang;
    private javax.swing.JComboBox<String> cbx_Loi_BaoHanh;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_DiaChiKhachHang;
    private javax.swing.JLabel lbl_GiaTien_LK;
    private javax.swing.JLabel lbl_HoKhachHang;
    private javax.swing.JLabel lbl_MaKhachHang;
    private javax.swing.JLabel lbl_SoChungMinh;
    private javax.swing.JLabel lbl_SoDienThoai;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_TenLinhKien_LK;
    private javax.swing.JLabel lbl_TimKiem_BH;
    private javax.swing.JLabel lbl_TimLinhKien_LK;
    private javax.swing.JTable myTable_BaoHanh;
    private javax.swing.JTable myTable_LinhKien;
    private javax.swing.JPanel pn_Baohanh;
    private javax.swing.JPanel pn_ChiTietKhachHang;
    private javax.swing.JTabbedPane pn_XeMay_KhachHang;
    private javax.swing.JTextField txt_DiaChi_BH;
    private javax.swing.JTextField txt_GiaTien_BH;
    private javax.swing.JTextField txt_GiaTien_LK;
    private javax.swing.JTextField txt_LinhKien_BH;
    private javax.swing.JTextField txt_LyDo_BH;
    private javax.swing.JTextField txt_MaBaoHanh_BH;
    private javax.swing.JTextField txt_MaXe_BH;
    private javax.swing.JTextField txt_NhanVien_BH;
    private javax.swing.JTextField txt_SoChungMinh;
    private javax.swing.JTextField txt_TenKhachHang_BH;
    private javax.swing.JTextField txt_Ten_LK;
    private javax.swing.JTextField txt_TimKiem_BH;
    private javax.swing.JTextField txt_TimKiem_LK;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("empty-statement")
    private void loadDataBaoHanh() {
        ArrayList<HeThongBaoHanh> list = ds_BaoHanh.getArr();
        for (int i = 0; i < list.size(); i++) {
            int maBaoHanh = list.get(i).getMaBaoHanh();
            String maBH = Integer.toString(maBaoHanh);
            String tenKhachHang = list.get(i).getTenKhachHang();
            int maXe = list.get(i).getMaXe();
            String maX = Integer.toString(maXe);
            String lyDo = list.get(i).getLyDo();
            String loi = list.get(i).getLoiThuocVe();
            String linhKien = list.get(i).getLinhKien();
            double giaTien = list.get(i).getGiaTien();
            String giaT = Double.toString(giaTien);
            String nhanVienBH = list.get(i).getNhanVienBaoHanh();
            String diaChi = list.get(i).getDiaChi();
            String rowData[] = {maBH, tenKhachHang, maX, lyDo, loi, linhKien, giaT, nhanVienBH, diaChi};
            DefaultTableModel tableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
            tableModel.addRow(rowData);
        }
        //   cbx_Loi_BaoHanh.setSelectedIndex(0);
        txt_MaBaoHanh_BH.setEnabled(false);

    }

    private void xoaTrangBH() {
        txt_MaBaoHanh_BH.setText("");
        txt_TenKhachHang_BH.setText("");
        txt_MaXe_BH.setText("");
        txt_LyDo_BH.setText("");
        cbx_Loi_BaoHanh.setSelectedIndex(0);
        txt_LinhKien_BH.setText("");
        txt_GiaTien_BH.setText("");
        txt_NhanVien_BH.setText("");
        txt_TimKiem_BH.setText("");
        txt_DiaChi_BH.setText("");
        btn_PhatSinhMaBH.setEnabled(true);
        btn_Them_BH.setEnabled(true);
        txt_Ten_LK.setText("");
        txt_GiaTien_LK.setText("");
    }

    private void themBH() throws ClassNotFoundException, SQLException {
        int a = nhapLieuBH();
        if (a == 0) {
            try {
                String maBH = txt_MaBaoHanh_BH.getText();
                JOptionPane.showMessageDialog(this, maBH);
                int maBaoHanh = Integer.parseInt(maBH);
                String tenKhachHang = txt_TenKhachHang_BH.getText();
                
                JOptionPane.showMessageDialog(this, tenKhachHang);
                String maX = txt_MaXe_BH.getText();
                
                JOptionPane.showMessageDialog(this, maX);
                int maXe = Integer.parseInt(maX);
                String lyDo = txt_LyDo_BH.getText();

                JOptionPane.showMessageDialog(this, lyDo);
                int loi = cbx_Loi_BaoHanh.getSelectedIndex();
                String loiThuocVe = cbx_Loi_BaoHanh.getItemAt(loi);
                
                JOptionPane.showMessageDialog(this, loiThuocVe);
                String linhKien = txt_LinhKien_BH.getText();
                
                JOptionPane.showMessageDialog(this, linhKien);
                String giaT = txt_GiaTien_BH.getText();
                
                JOptionPane.showMessageDialog(this,giaT);
                double giaTien = Double.parseDouble(giaT);

                String nhanVienBH = txt_NhanVien_BH.getText();
                
                JOptionPane.showMessageDialog(this, nhanVienBH);
                String diaChi = txt_DiaChi_BH.getText();
                
                JOptionPane.showMessageDialog(this, diaChi);
                HeThongBaoHanh hTBH = new HeThongBaoHanh(maBaoHanh, tenKhachHang, maXe, lyDo, loiThuocVe,
                        linhKien, giaTien, nhanVienBH, diaChi);

                if (ds_BaoHanh.themBaoHanh(hTBH)) {
                    String rowData[] = {maBH, tenKhachHang, maX,
                        lyDo, loiThuocVe, linhKien, giaT, nhanVienBH, diaChi};
                    DefaultTableModel tableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
                    tableModel.addRow(rowData);

                    ds_BaoHanh.themSQLBaoHanh(maBaoHanh, tenKhachHang, maXe, lyDo, loiThuocVe, linhKien, giaTien,
                            nhanVienBH, diaChi);
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    
                    int row = myTable_BaoHanh.getRowCount();
                    xoaTrangBH();
                } else {
                    JOptionPane.showMessageDialog(this, "Trùng mã");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thêm Không Thành Công!");
            }
        } else {
            switch (a) {
                
                case 2: {
                    JOptionPane.showMessageDialog(this, "Tên khách hàng sai định dạng");
                    break;
                }
                case 3: {
                    JOptionPane.showMessageDialog(this, "Mã xe sai định dạng");
                    break;
                }
                case 5: {
                    JOptionPane.showMessageDialog(this, "Linh kiện là chuỗi kí tự");
                    break;
                }
                case 6: {
                    JOptionPane.showMessageDialog(this, "Giá tiền là số");
                    break;
                }
                case 7: {
                    JOptionPane.showMessageDialog(this, "Tên nhân viên không đúng định dạng");
                    break;
                }
                case 8: {
                    JOptionPane.showMessageDialog(this, "Địa chỉ không đúng định dạng");
                    break;
                }
                
                case 9: {
                    JOptionPane.showMessageDialog(this, "Mã xe không có trong hợp đồng");
                    break;
                }
                case 10:{
                    JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ thông tin" );
                    break;
                }
            }
        }

    }

    private int nhapLieuBH() throws ClassNotFoundException, SQLException {

        if (txt_MaXe_BH.getText().trim().isEmpty() || txt_MaBaoHanh_BH.getText().trim().isEmpty() || txt_TenKhachHang_BH.getText().trim().isEmpty()|| txt_LyDo_BH.getText().trim().isEmpty()||
                txt_LinhKien_BH.getText().trim().isEmpty() || txt_DiaChi_BH.getText().trim().isEmpty() || txt_NhanVien_BH.getText().trim().isEmpty()){
            return 10;
        }
        else{
            if (!Pattern.matches("^[a-zA-Z\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_TenKhachHang_BH.getText()))
                return 2;
            if (!Pattern.matches("^[0-9]+", txt_MaXe_BH.getText()))
                return 3;
            if (!Pattern.matches("^[a-zA-Z0-9\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_LinhKien_BH.getText()))
                return 5;
            if (!Pattern.matches("[0-9]+(.)[0-9]+", txt_GiaTien_BH.getText()) && !Pattern.matches("[0-9]+", txt_GiaTien_BH.getText()))
                return 6;
            if (!Pattern.matches("^[a-zA-Z\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_NhanVien_BH.getText()))
                return 7;
            if (!Pattern.matches("^[a-zA-Z0-9\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_DiaChi_BH.getText()))
                return 8;
            if (!txt_MaXe_BH.getText().trim().isEmpty()){
                String maXe = txt_MaXe_BH.getText();
                int maX = Integer.parseInt(maXe);
                if (!ds_BaoHanh.doiChieuMaXe1Lan(maX) && !ds_BaoHanh.doiChieuMaXeTraGop(maX))
                return 9;
            }
            
            return 0;
        }
        
        
    }

    private int phatSinhMBH() {
        Random rd = new Random();
        int maBH = rd.nextInt(1000000);
        return maBH;
    }

    private void xoaBaoHanh() throws ClassNotFoundException, SQLException {
        int row = myTable_BaoHanh.getSelectedRow();
        if (row >= 0) {
            String maBaoHanh = (String) myTable_BaoHanh.getValueAt(row, 0);
            int maBH = Integer.parseInt(maBaoHanh);
            HeThongBaoHanh bh = new HeThongBaoHanh(maBH);
            int hoiNhac = JOptionPane.showConfirmDialog(this, "Chú ý", "Bạn Muốn Xóa Không", JOptionPane.YES_NO_OPTION);
            if (hoiNhac == JOptionPane.YES_OPTION) {
                if (ds_BaoHanh.xoaBaoHanh(bh)) {
                    DefaultTableModel tableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
                    tableModel.removeRow(row);
                    ds_BaoHanh.xoaSQLBaoHanh(maBH);
                    JOptionPane.showMessageDialog(this, "Xoá thành công!");
                    
                }
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để xóa");

    }

    public void capNhatBaoHanh() {
        int row = myTable_BaoHanh.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để cập nhật");
        else{
            try {
                String maBH = myTable_BaoHanh.getValueAt(row, 0).toString();
                int maBaoHanh = Integer.parseInt(maBH);

                String tenKH = txt_TenKhachHang_BH.getText();
                String maX = myTable_BaoHanh.getValueAt(row, 2).toString();
                int maXe = Integer.parseInt(maX);
                String lyDo = txt_LyDo_BH.getText();
                int viTri = cbx_Loi_BaoHanh.getSelectedIndex();
                String loi = cbx_Loi_BaoHanh.getItemAt(viTri);
                String linhKien = txt_LinhKien_BH.getText();
                String giaT = txt_GiaTien_BH.getText();
                double giaTien = Double.parseDouble(giaT);
                String nhanVienBaoHanh = txt_NhanVien_BH.getText();
                String diaChi = txt_DiaChi_BH.getText();
                HeThongBaoHanh bhMoi = new HeThongBaoHanh(maBaoHanh, tenKH, maXe, lyDo,
                        loi, linhKien, giaTien, nhanVienBaoHanh, diaChi);

                if (ds_BaoHanh.capNhatBaoHanh(maBaoHanh, bhMoi)) {

                    DefaultTableModel tableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
                    tableModel.setValueAt(bhMoi.getMaBaoHanh(), row, 0);
                    tableModel.setValueAt(bhMoi.getTenKhachHang(), row, 1);
                    tableModel.setValueAt(bhMoi.getMaXe(), row, 2);
                    tableModel.setValueAt(bhMoi.getLyDo(), row, 3);
                    tableModel.setValueAt(bhMoi.getLoiThuocVe(), row, 4);
                    tableModel.setValueAt(bhMoi.getLinhKien(), row, 5);
                    tableModel.setValueAt(bhMoi.getGiaTien(), row, 6);
                    tableModel.setValueAt(bhMoi.getNhanVienBaoHanh(), row, 7);
                    tableModel.setValueAt(bhMoi.getDiaChi(), row, 8);
                    ds_BaoHanh.capNhatSQLBaoHanh(maBaoHanh, tenKH, maXe, lyDo, loi, linhKien, giaTien,
                            nhanVienBaoHanh, diaChi);
                    JOptionPane.showMessageDialog(this, "Cap Nhat Thanh Cong!");
                } else {
                    JOptionPane.showMessageDialog(this, "Khong cap nhat duoc");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Nhập sai");
            }
        }

    }

        private void timKiemBaoHanh() {
            try {
                String KhoaTimKiem = txt_TimKiem_BH.getText();

                if (KhoaTimKiem.equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(this, "Nhập thông tin để tìm kiếm");

                } else if (Pattern.matches("[0-9]+", KhoaTimKiem)) {

                    int khoa = Integer.parseInt(KhoaTimKiem);
                    HeThongBaoHanh bh = new HeThongBaoHanh(khoa);
                    int viTriBH = ds_BaoHanh.timKiemMaBH_BH(bh);
                    if (viTriBH != -1) {
                        myTable_BaoHanh.setRowSelectionInterval(viTriBH, viTriBH);
                        int row = myTable_BaoHanh.getSelectedRow() + 1;
                        String rowTimKiem = Integer.toString(row);
                        JOptionPane.showMessageDialog(this, "Đã tìm thấy ở hàng thứ   " + rowTimKiem);
                    } else {

                        ds_BaoHanh.xoaJframeDuLieu();

                        DefaultTableModel table_Model = (DefaultTableModel) myTable_BaoHanh.getModel();

                        table_Model.setRowCount(0);

                        int dem = timKiemMaXe_BH(khoa);
                        if (dem == 0) {
                            JOptionPane.showMessageDialog(this, "Không tìm thấy !");
                        }

                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Sai định dạng!");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

    }

    private int timKiemMaXe_BH(int maXe) throws ClassNotFoundException, SQLException {
        ds_TimKiemMaXe_BH = new DanhSachBaoHanh();
        ds_TimKiemMaXe_BH.timKiemSQLMaXeMay_BH(maXe);
        ArrayList<HeThongBaoHanh> list = ds_TimKiemMaXe_BH.getArr();

        int a = 0;
        for (int i = 0; i < list.size(); i++) {
            int maBaoHanh = list.get(i).getMaBaoHanh();
            String maBH = Integer.toString(maBaoHanh);
            String tenKhachHang = list.get(i).getTenKhachHang();
            int maXeBaoHanh = list.get(i).getMaXe();
            String maX = Integer.toString(maXeBaoHanh);
            String lyDo = list.get(i).getLyDo();
            String loi = list.get(i).getLoiThuocVe();
            String linhKien = list.get(i).getLinhKien();
            double giaTien = list.get(i).getGiaTien();
            String giaT = Double.toString(giaTien);
            String nhanVienBH = list.get(i).getNhanVienBaoHanh();
            String diaChi = list.get(i).getDiaChi();

            String rowData[] = {maBH, tenKhachHang, maX, lyDo, loi, linhKien, giaT, nhanVienBH, diaChi};
            DefaultTableModel TableModel = (DefaultTableModel) myTable_BaoHanh.getModel();
            TableModel.addRow(rowData);
            a++;

        }

        cbx_Loi_BaoHanh.setSelectedIndex(0);
        txt_MaBaoHanh_BH.setEnabled(false);
        int row = myTable_BaoHanh.getRowCount();
        return a;
    }

    public void inPhieuBaoHanh() throws FileNotFoundException {
        
        int row = myTable_BaoHanh.getSelectedRow();
        if (row == -1 )
            JOptionPane.showMessageDialog(this, "Chưa chọn thuộc tính để in phiếu");
        else {
            String maBH = myTable_BaoHanh.getValueAt(row, 0).toString();
            int maBaoHanh = Integer.parseInt(maBH);

            String tenKH = txt_TenKhachHang_BH.getText();
            String maX = myTable_BaoHanh.getValueAt(row, 2).toString();
            int maXe = Integer.parseInt(maX);
            String lyDo = txt_LyDo_BH.getText();
            int viTri = cbx_Loi_BaoHanh.getSelectedIndex();
            String loi = cbx_Loi_BaoHanh.getItemAt(viTri);
            String linhKien = txt_LinhKien_BH.getText();
            String giaT = txt_GiaTien_BH.getText();
            double giaTien = Double.parseDouble(giaT);
            String nhanVienBaoHanh = txt_NhanVien_BH.getText();
            String diaChi = txt_DiaChi_BH.getText();
            BufferedWriter bw = null;
            FileWriter fw = null;
            try {
                File file = new File("inPhieu.txt");
                if (file.exists()) {
                    file.delete();
                }
                file.createNewFile();

                fw = new FileWriter(file.getAbsoluteFile(), true);
                bw = new BufferedWriter(fw);
                bw.write("...::: Phiếu bảo hành của khách hàng :::...\r\n");
                bw.write("\r\nMã bảo hành        :       ");
                bw.write(maBH);
                bw.write("\r\nTên khách hàng     :       ");
                bw.write(tenKH);
                bw.write("\r\nMã xe              :       ");
                bw.write(maX);
                bw.write("\r\nLý do              :       ");
                bw.write(lyDo);
                bw.write("\r\nLỗi thuộc về       :       ");
                bw.write(loi);
                bw.write("\r\nLinh kiện          :       ");
                bw.write(linhKien);
                bw.write("\r\nGiá tiền           :       ");
                bw.write(giaT);
                bw.write("\r\nNhân viên bảo hành :       ");
                bw.write(nhanVienBaoHanh);
                bw.write("\r\nĐịa chỉ bảo hành   :       ");
                bw.write(diaChi);
                String ngayThang = "Tp HCM thứ     ngày     tháng    năm     ";
                String kiTen = "Ký tên";
                bw.write("\r\n\r\n                             " + ngayThang);
                bw.write("\r\n\r\n                                             " + kiTen);

                JOptionPane.showMessageDialog(this, "Phiếu in đã đưa vào file inPhieu");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    if (bw != null) {
                        bw.close();
                    }
                    if (fw != null) {
                        fw.close();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

    }
    public void themLK_LK() throws ClassNotFoundException, SQLException{
        
        int a = nhapLieuLK();
        
        if (a == 0){
            String tenLK = txt_Ten_LK.getText();
            String gia = txt_GiaTien_LK.getText();
            double giaTien = Double.parseDouble(gia);
            LinhKien lk = new LinhKien( tenLK, giaTien);
            if (ds_LinhKien.themLinhKien(lk)){
            
                String rowData[] = {tenLK, gia};
                DefaultTableModel tableModel = (DefaultTableModel) myTable_LinhKien.getModel();
                tableModel.addRow(rowData);
                ds_LinhKien.themSQLLinhKien(tenLK, giaTien);
                JOptionPane.showMessageDialog(this, "Thêm thành công");

            }
            else {
                JOptionPane.showMessageDialog(this, "Linh kiện đã có");
            }
        }
        else{
                switch (a){
                    
                    case 2:{
                        JOptionPane.showMessageDialog(this, "Tên linh kiện sai định dạng");
                        break;
                    }
                    case 3:{
                        JOptionPane.showMessageDialog(this, "Giá tiền sai định dạng");
                        break;
                    }
                    case 4:{
                        JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ thông tin");
                    }
                }
        }
        
    }
    public int nhapLieuLK(){
        if (txt_Ten_LK.getText().trim().isEmpty() || 
                txt_GiaTien_LK.getText().trim().isEmpty())
            return 4;
        if (!Pattern.matches("^[a-zA-Z0-9\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}",txt_Ten_LK.getText()))
            return 2;
        if (!Pattern.matches("[0-9]+", txt_GiaTien_LK.getText()) && !Pattern.matches("[0-9]+(.)[0-9]+", txt_GiaTien_LK.getText()))
            return 3;
        return 0;
    }
    private void loadDataLinhKien() throws ClassNotFoundException {

        ArrayList<LinhKien> list  = ds_LinhKien.getArr();
        for (int i=0; i<list.size(); i++){
            String tenLK = list.get(i).getTenLinhKien();
            double gia = list.get(i).getGiaTienLinhKien();
            String giaTien = Double.toString(gia);
            String rowData[] = {tenLK, giaTien};
            DefaultTableModel tableModel = (DefaultTableModel) myTable_LinhKien.getModel();
            tableModel.addRow(rowData);
        }
    }
    public void xoaLinhKien(){
        int row = myTable_LinhKien.getSelectedRow();
        if(row == -1)
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để xóa");
        else{
            String ten = myTable_LinhKien.getValueAt(row, 0).toString();
            String gia = myTable_LinhKien.getValueAt(row, 1).toString();
            double giaTien = Double.parseDouble(gia);
            LinhKien lk = new LinhKien(ten, giaTien);
            if (ds_LinhKien.xoaLinhKien(lk)){
                DefaultTableModel tableModel = (DefaultTableModel) myTable_LinhKien.getModel();
                tableModel.removeRow(row);
                ds_LinhKien.xoaSQLLinhKien(ten);
                JOptionPane.showMessageDialog(this, "Xóa thành công");

            }
        }
    }
    public void timKiemLK(){
        String tenLK = txt_TimKiem_LK.getText();
        int a = ds_LinhKien.timKiem(tenLK);
        if (a != -1){
            myTable_LinhKien.setRowSelectionInterval(a, a);
        }
        else
            JOptionPane.showMessageDialog(this ,"Không tìm thấy linh kiện");
    }
    public void huyLK() throws ClassNotFoundException{
        txt_TimKiem_LK.setText("");
        txt_Ten_LK.setText("");
        txt_GiaTien_LK.setText("");
        DefaultTableModel tableModel = (DefaultTableModel) myTable_LinhKien.getModel();
        tableModel.setRowCount(0);
        ds_LinhKien.layDuLieu();
        loadDataLinhKien();
        txt_Ten_LK.setEnabled(true);
    }
    public void capNhatLK(){
        int row = myTable_LinhKien.getSelectedRow();
        if (row == -1)
            JOptionPane.showMessageDialog(this, "Chọn một dòng để cập nhật");
        else{
            String tenLK = txt_Ten_LK.getText();
            String gia = txt_GiaTien_LK.getText();
            double giaTien = Double.parseDouble(gia);
            LinhKien lkMoi = new LinhKien(tenLK, giaTien);
            if(ds_LinhKien.capNhatLK(tenLK, lkMoi)){
                DefaultTableModel tableModel = (DefaultTableModel) myTable_LinhKien.getModel();
                tableModel.setValueAt(lkMoi.getTenLinhKien(), row, 0);
                tableModel.setValueAt(lkMoi.getGiaTienLinhKien(), row, 1);
                ds_LinhKien.capNhatSQLLK(tenLK, giaTien);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
            else{
                JOptionPane.showMessageDialog(this, "Không cập nhật được");
            }
        }
        
    }
   


}
