/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_DangNhap_DangXuat_DoiMatKhau;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ThanhTam
 */
public class Gui_DoiMatKhau extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Gui_DoiMatKhau
     */
    public Gui_DoiMatKhau() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_MatKhauCu = new javax.swing.JLabel();
        lbl_NhapLaiMatKhau = new javax.swing.JLabel();
        lbl_MatKhauMoi = new javax.swing.JLabel();
        txt_MatKhauCu = new javax.swing.JPasswordField();
        txt_MatKhauMoi = new javax.swing.JPasswordField();
        txt_NhapLaiMatKhau = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        lbl_MaNhanVien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mật khẩu cũ:");

        jLabel2.setText("Mật khẩu mới :");

        jLabel3.setText("Nhập lại mật khẩu : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Cửa Hàng Xe Máy");

        lbl_MatKhauCu.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        lbl_NhapLaiMatKhau.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        lbl_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        txt_MatKhauCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauCuActionPerformed(evt);
            }
        });

        txt_MatKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauMoiActionPerformed(evt);
            }
        });

        txt_NhapLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhapLaiMatKhauActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:confirm.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Huy.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        lbl_MaNhanVien.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(72, 72, 72)
                                .addComponent(txt_NhapLaiMatKhau))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lbl_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lbl_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_Huy))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NhapLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhapLaiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NhapLaiMatKhauActionPerformed

    private void txt_MatKhauCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauCuActionPerformed

    private void txt_MatKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        datLai();
        if (txt_MatKhauCu.getText().trim().isEmpty() || txt_MatKhauMoi.getText().trim().isEmpty()
                || txt_NhapLaiMatKhau.getText().trim().isEmpty()) {

            if (txt_MatKhauCu.getText().trim().isEmpty()) {
                lbl_MatKhauCu.setText("Bạn chưa điền mục này");
            }
            if (txt_MatKhauMoi.getText().trim().isEmpty()) {
                lbl_MatKhauMoi.setText("Bạn chưa điền mục này");
            }
            if (txt_NhapLaiMatKhau.getText().trim().isEmpty()) {
                lbl_NhapLaiMatKhau.setText("Bạn chưa điền mục này");
            }

        } else {

            datLai();
            String matKhauMoi = txt_MatKhauMoi.getText();
            String nhapLaiMatKhau = txt_NhapLaiMatKhau.getText();

            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;" + "databaseName=quanli;user=sa;password=123";

                conn = DriverManager.getConnection(url);

                String sql = "select * from taikhoan where passwords=?";
                pst = conn.prepareStatement(sql);

                pst.setString(1, txt_MatKhauCu.getText());
                rs = pst.executeQuery();
                if (rs.next()) {
                    if (!matKhauMoi.equalsIgnoreCase(nhapLaiMatKhau)) {
                        lbl_NhapLaiMatKhau.setText("Nhập lại chưa đúng");
                    } else {
                        int hoiNhac = JOptionPane.showConfirmDialog(this, "Bạn có muốn thay đổi",
                                "Chú Ý", JOptionPane.YES_NO_OPTION);
                        if (hoiNhac == JOptionPane.YES_OPTION) {
                            doiMatKhau();
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Nhập sai mật khẩu cũ!");
                    txt_MatKhauCu.setText("");
                    txt_MatKhauMoi.setText("");
                    txt_NhapLaiMatKhau.setText("");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Nhập sai định dạng!");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        int hoinhac = JOptionPane.showConfirmDialog(this, "Bạn muốn hủy", "Chú ý",
                JOptionPane.YES_NO_OPTION);
        if (hoinhac == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public void datLai() {
//        txt_MaNhanVien.setText("");
//        txt_MatKhauCu.setText("");
//        txt_MatKhauMoi.setText("");
//        txt_NhapLaiMatKhau.setText("");
        lbl_MaNhanVien.setText("");
        lbl_MatKhauCu.setText("");
        lbl_MatKhauMoi.setText("");
        lbl_NhapLaiMatKhau.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_MaNhanVien;
    private javax.swing.JLabel lbl_MatKhauCu;
    private javax.swing.JLabel lbl_MatKhauMoi;
    private javax.swing.JLabel lbl_NhapLaiMatKhau;
    private javax.swing.JPasswordField txt_MatKhauCu;
    private javax.swing.JPasswordField txt_MatKhauMoi;
    private javax.swing.JPasswordField txt_NhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables

    private void doiMatKhau() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;" + "databaseName=quanli;user=sa;password=123";
            conn = DriverManager.getConnection(url);

            String sql_select = "select username from taikhoan where passwords = ?";
            PreparedStatement prsttm = conn.prepareStatement(sql_select);
            prsttm.setString(1, txt_MatKhauCu.getText());
            rs = prsttm.executeQuery();
            while (rs.next()) {
                String user = rs.getString(1);
                String sql_update = "update taikhoan set passwords=? where username = ? ";
                pst = conn.prepareStatement(sql_update);

                pst.setString(1, txt_MatKhauMoi.getText());
                pst.setString(2, user);
                pst.executeUpdate();

            }

            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
}
