/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Hopdongs;

import QuanLiHopDong.DanhSach_HopDong1Lan;
import QuanLiHopDong.HopDong1Lan;
import QuanLiKhachHang.DanhSachKhachHang;
import QuanLiKhachHang.KhachHang;
import QuanLiXeMay.DanhSachXeMay;
import QuanLiXeMay.XeMay;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Dat
 */
public class GUI_HopDong1Lan extends javax.swing.JFrame {

    /**
     * Creates new form HopDong1Lan
     */
    // private DanhSachXeMay ds_XeMay;
    private DanhSach_HopDong1Lan ds_HopDong_1Lan;
    private DanhSachKhachHang ds_KhachHang;
    private DanhSachXeMay ds_XeMay;

    public GUI_HopDong1Lan() throws ClassNotFoundException {
        super("...::: Hợp đồng 1 lần :::...");
        initComponents();

        ds_HopDong_1Lan = new DanhSach_HopDong1Lan();
        ds_HopDong_1Lan.docTuBang();

        ds_KhachHang = new DanhSachKhachHang();
        ds_XeMay = new DanhSachXeMay();

        LoadData_HopDong_1Lan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_SoHopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_NgayLapHopDong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ThoiGianBaoHanh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        txt_SoLuongXeMua = new javax.swing.JTextField();
        txt_GiamGia = new javax.swing.JTextField();
        txt_NhanVienThanhToan = new javax.swing.JTextField();
        txt_LoaiHopDong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_MaKhachHang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_HoKhachHang = new javax.swing.JTextField();
        txt_TenKhachHang = new javax.swing.JTextField();
        txt_SoDienThoai = new javax.swing.JTextField();
        txt_SoChungMinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DiaChi = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_MaXe = new javax.swing.JTextField();
        txt_HangXe = new javax.swing.JTextField();
        txt_DongXe = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_GiaXe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_Them_HopDong_1Lan = new javax.swing.JButton();
        btn_LayThongTin_KhachHang = new javax.swing.JButton();
        btn_PhatSinh_SoHopDong = new javax.swing.JButton();
        btn_LamMoi_HopDong = new javax.swing.JButton();
        btn_LayThongTin_XeMay = new javax.swing.JButton();
        btn_TinhTien = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        myTable_HopDong_1Lan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin chi tiết hợp đồng - 1 lần");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Hợp đồng :::..."));

        jLabel2.setText("Số hợp đồng");

        jLabel4.setText("Thời gian bảo hành (tháng)");

        jLabel5.setText("Tổng tiền (triệu)");

        jLabel6.setText("Số lượng xe mua (chiếc)");

        jLabel7.setText("Giảm giá (%)");

        jLabel8.setText("Nhân viên thanh toán");

        jLabel9.setText("Loại hợp đồng");

        jLabel10.setText("Ngày lập hợp đồng");

        txt_TongTien.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_TongTien.setForeground(new java.awt.Color(255, 0, 0));

        txt_SoLuongXeMua.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_SoLuongXeMua.setForeground(new java.awt.Color(0, 0, 0));
        txt_SoLuongXeMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoLuongXeMuaActionPerformed(evt);
            }
        });
        txt_SoLuongXeMua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SoLuongXeMuaKeyPressed(evt);
            }
        });

        txt_GiamGia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_GiamGia.setForeground(new java.awt.Color(255, 0, 0));
        txt_GiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_GiamGiaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_SoHopDong)
                    .addComponent(txt_NgayLapHopDong)
                    .addComponent(txt_ThoiGianBaoHanh)
                    .addComponent(txt_TongTien)
                    .addComponent(txt_SoLuongXeMua)
                    .addComponent(txt_GiamGia)
                    .addComponent(txt_NhanVienThanhToan)
                    .addComponent(txt_LoaiHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_SoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NgayLapHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_SoLuongXeMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_NhanVienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_LoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("...::: Khách hàng :::...")));

        jLabel11.setText("Mã khách hàng");

        jLabel12.setText("Họ khách hàng");

        jLabel13.setText("Tên khách hàng");

        jLabel14.setText("Địa chỉ");

        jLabel15.setText("Số điện thoại");

        jLabel16.setText("Số chứng minh");

        txt_SoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoDienThoaiActionPerformed(evt);
            }
        });

        txt_DiaChi.setColumns(20);
        txt_DiaChi.setRows(5);
        jScrollPane1.setViewportView(txt_DiaChi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_HoKhachHang)
                    .addComponent(txt_TenKhachHang)
                    .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SoChungMinh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_HoKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_SoChungMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Xe máy :::..."));

        jLabel17.setText("Mã xe");

        jLabel18.setText("Hãng xe");

        jLabel19.setText("Dòng xe");

        jLabel20.setText("Giá mỗi chiếc (triệu)");

        jLabel21.setText("Số lượng còn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaXe)
                    .addComponent(txt_HangXe)
                    .addComponent(txt_DongXe)
                    .addComponent(txt_GiaXe)
                    .addComponent(txt_SoLuong))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_MaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_HangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_DongXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_GiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btn_Them_HopDong_1Lan.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:add.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Them_HopDong_1Lan.setText("Thêm");
        btn_Them_HopDong_1Lan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them_HopDong_1LanActionPerformed(evt);
            }
        });

        btn_LayThongTin_KhachHang.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:customer.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LayThongTin_KhachHang.setText("Lấy thông tin khách hàng");
        btn_LayThongTin_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LayThongTin_KhachHangActionPerformed(evt);
            }
        });

        btn_PhatSinh_SoHopDong.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:create.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_PhatSinh_SoHopDong.setText("Phát sinh số hợp đồng");
        btn_PhatSinh_SoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhatSinh_SoHopDongActionPerformed(evt);
            }
        });

        btn_LamMoi_HopDong.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:renew.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LamMoi_HopDong.setText("Làm mới");
        btn_LamMoi_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_HopDongActionPerformed(evt);
            }
        });

        btn_LayThongTin_XeMay.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:motorbike.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LayThongTin_XeMay.setText("Lấy thông tin xe máy");
        btn_LayThongTin_XeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LayThongTin_XeMayActionPerformed(evt);
            }
        });

        btn_TinhTien.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:sum.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_TinhTien.setText("Tính tổng tiền");
        btn_TinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTienActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_PhatSinh_SoHopDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Them_HopDong_1Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LamMoi_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TinhTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LayThongTin_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LayThongTin_XeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them_HopDong_1Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LayThongTin_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PhatSinh_SoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LayThongTin_XeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        myTable_HopDong_1Lan.setAutoCreateRowSorter(true);
        myTable_HopDong_1Lan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hợp đồng", "Ngày lập", "Thời gian bảo hành", "Tổng tiền", "Số lượng xe mua", "Giảm giá", "Nhân viên thanh toán", "Loại hợp đồng", "Mã khách hàng", "Họ", "Tên", "Địa chỉ", "Số điện thoại", "Số chứng minh", "Mã xe", "Hãng", "Dòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable_HopDong_1Lan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTable_HopDong_1LanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myTable_HopDong_1Lan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoDienThoaiActionPerformed

    private void btn_LamMoi_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_HopDongActionPerformed
        // TODO add your handling code here:
        XoaTrang_HopDong_1Lan();
    }//GEN-LAST:event_btn_LamMoi_HopDongActionPerformed

    private void btn_LayThongTin_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LayThongTin_KhachHangActionPerformed
        // TODO add your handling code here:

        String maKhachHang = txt_MaKhachHang.getText();
        if (maKhachHang.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng trống!");
        } else {
            try {
                ds_KhachHang.docTimKiem_MaKhachHang_SQL(Integer.parseInt(maKhachHang));
                ArrayList<KhachHang> list = ds_KhachHang.getDsKhachHang();
                for (int i = 0; i < list.size(); i++) {

                    String HoKhachHang = list.get(i).getHoKhachHang();
                    String TenKhachHang = list.get(i).getTenKhachHang();
                    String DiaChi = list.get(i).getDiaChiKhachHang();
                    String SoDienThoai = list.get(i).getSoDienThoaiKhachHang();
                    String SoChungMinh = list.get(i).getSoChungMinhKhachHang();

                    txt_HoKhachHang.setText(HoKhachHang);
                    txt_TenKhachHang.setText(TenKhachHang);
                    txt_DiaChi.setText(DiaChi);
                    txt_SoDienThoai.setText(SoDienThoai);
                    txt_SoChungMinh.setText(SoChungMinh);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btn_LayThongTin_KhachHangActionPerformed

    private void btn_LayThongTin_XeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LayThongTin_XeMayActionPerformed
        // TODO add your handling code here:\
        String maXe = txt_MaXe.getText();

        if (maXe.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mã xe trống");
        } else {
            try {
                int MaXe = Integer.parseInt(maXe);
                ds_XeMay.docTimKiem_MaXeMay_TuBang_SQL(MaXe);
                ArrayList<XeMay> list = ds_XeMay.getDsXeMay();
                for (int i = 0; i < list.size(); i++) {
                    String HangXe = list.get(i).getHangXe();
                    String DongXe = list.get(i).getDongXe();
                    float GiaXe = list.get(i).getGiaXe();
                    String giaXe = Float.toString(GiaXe);
                    int SoLuong = list.get(i).getSoLuong();
                    String soLuong = Integer.toString(SoLuong);
                    txt_HangXe.setText(HangXe);
                    txt_DongXe.setText(DongXe);
                    txt_GiaXe.setText(giaXe);
                    txt_SoLuong.setText(soLuong);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btn_LayThongTin_XeMayActionPerformed

    private void btn_PhatSinh_SoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhatSinh_SoHopDongActionPerformed
        // TODO add your handling code here:
        Random rd = new Random();
        int so = rd.nextInt(1000000);
        txt_SoHopDong.setText(Integer.toString(so));
    }//GEN-LAST:event_btn_PhatSinh_SoHopDongActionPerformed

    private void txt_SoLuongXeMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoLuongXeMuaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_SoLuongXeMuaActionPerformed


    private void btn_TinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTienActionPerformed
        // TODO add your handling code here:

        String soLuong = txt_SoLuongXeMua.getText();
        String giaTien = txt_GiaXe.getText();
        String giamGia = txt_GiamGia.getText();
        String soLuongCon = txt_SoLuong.getText();

        if (soLuong.isEmpty() || giaTien.isEmpty() || giamGia.isEmpty() || soLuongCon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng rỗng hoặc chưa lấy thông tin xe máy\n hoặc chưa nhập giảm giá");
        } else {
            int SoLuongCon = Integer.parseInt(soLuongCon);
            int SoLuong = Integer.parseInt(soLuong);
            if (SoLuong <= SoLuongCon) {
                float GiaTien = Float.parseFloat(giaTien);
                float GiamGia = Float.parseFloat(giamGia);
                float tongTien = SoLuong * GiaTien - (SoLuong * GiaTien) * GiamGia / 100;
                txt_TongTien.setText(Float.toString(tongTien));
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng mua phải nhỏ hơn hoặc bằng số lượng xe còn.\n Yêu cầu bộ phận bán hàng nhập thêm xe!");
            }

        }


    }//GEN-LAST:event_btn_TinhTienActionPerformed

    private void btn_Them_HopDong_1LanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them_HopDong_1LanActionPerformed
        // TODO add your handling code here:
        if (KiemTraInput_HopDong() == 0) {

            try {
                String soHopDong = txt_SoHopDong.getText();
                int SoHopDong = Integer.parseInt(soHopDong);
                String ngayLapHopDong = txt_NgayLapHopDong.getText();

                String thoiGianBaoHanh = txt_ThoiGianBaoHanh.getText();
                int ThoiGianBaoHanh = Integer.parseInt(thoiGianBaoHanh);
                String tongTien = txt_TongTien.getText();
                float TongTien = Float.parseFloat(tongTien);
                String soLuongXeMua = txt_SoLuongXeMua.getText();
                int SoLuongXeMua = Integer.parseInt(soLuongXeMua);
                String giamGia = txt_GiamGia.getText();
                float GiamGia = Float.parseFloat(giamGia);
                String nhanVienThanhToan = txt_NhanVienThanhToan.getText();
                String loaiHopDong = txt_LoaiHopDong.getText();
                String maKhachHang = txt_MaKhachHang.getText();
                int MaKhachHang = Integer.parseInt(maKhachHang);
                String HoKhachHang = txt_HoKhachHang.getText();
                String TenKhachHang = txt_TenKhachHang.getText();
                String DiaChi = txt_DiaChi.getText();
                String SoDienThoai = txt_SoDienThoai.getText();
                String SoChungMinh = txt_SoChungMinh.getText();

                String maXe = txt_MaXe.getText();
                int MaXe = Integer.parseInt(maXe);
                String HangXe = txt_HangXe.getText();
                String DongXe = txt_DongXe.getText();

                HopDong1Lan hd = new HopDong1Lan(SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, SoLuongXeMua, GiamGia, nhanVienThanhToan, loaiHopDong, MaKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, MaXe, HangXe, DongXe);
                if (ds_HopDong_1Lan.Them_HopDong_1Lan(hd)) {
                    String row_Data[] = {soHopDong, ngayLapHopDong, thoiGianBaoHanh, tongTien, soLuongXeMua, giamGia, nhanVienThanhToan, loaiHopDong, maKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, maXe, HangXe, DongXe};
                    DefaultTableModel table_Model = (DefaultTableModel) myTable_HopDong_1Lan.getModel();
                    table_Model.addRow(row_Data);
                    ds_HopDong_1Lan.ThemHopDong_SQL(SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, SoLuongXeMua, GiamGia, nhanVienThanhToan, loaiHopDong, MaKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, MaXe, HangXe, DongXe);
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    XoaTrang_HopDong_1Lan();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            switch (KiemTraInput_HopDong()) {
                case 1: {
                    JOptionPane.showMessageDialog(this, "Hãy phát sinh số hợp đồng!");
                    break;
                }
                case 2: {
                    JOptionPane.showMessageDialog(this, "Nhập thời gian bảo hành là số nguyên dương\n Ví dụ: 12");
                    break;
                }
                case 3: {
                    JOptionPane.showMessageDialog(this, "Tổng tiền trống.");
                    break;
                }
                case 4: {
                    JOptionPane.showMessageDialog(this, "Nhập số lượng xe mua là số nguyên dương. Ví dụ: 3");
                    break;
                }
                case 5: {
                    JOptionPane.showMessageDialog(this, "Nhập giảm giá là số nguyên dương \n Ví dụ: 3.\n Có nghĩa là giảm 3%");
                    break;
                }
                case 6: {
                    JOptionPane.showMessageDialog(this, "Nhập nhân viên thanh toán là chuỗi kí tự \n Ví dụ: Nguyễn Thị Hồng ");
                    break;
                }
                case 7: {
                    JOptionPane.showMessageDialog(this, "Yêu cầu lấy thông tin khách hàng. \n Ví dụ: 23 ");
                    break;
                }
                case 8: {
                    JOptionPane.showMessageDialog(this, "Yêu cầu lấy thông tin xe!");
                    break;
                }

            }
        }
    }//GEN-LAST:event_btn_Them_HopDong_1LanActionPerformed

    private void myTable_HopDong_1LanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTable_HopDong_1LanMouseClicked
        // TODO add your handling code here:
        btn_PhatSinh_SoHopDong.setEnabled(false);
        btn_TinhTien.setEnabled(false);
        btn_Them_HopDong_1Lan.setEnabled(false);
        int row = myTable_HopDong_1Lan.getSelectedRow();
        txt_SoHopDong.setText(myTable_HopDong_1Lan.getValueAt(row, 0).toString());
        txt_NgayLapHopDong.setText(myTable_HopDong_1Lan.getValueAt(row, 1).toString());
        txt_ThoiGianBaoHanh.setText(myTable_HopDong_1Lan.getValueAt(row, 2).toString());
        txt_TongTien.setText(myTable_HopDong_1Lan.getValueAt(row, 3).toString());
        txt_SoLuongXeMua.setText(myTable_HopDong_1Lan.getValueAt(row, 4).toString());
        txt_GiamGia.setText(myTable_HopDong_1Lan.getValueAt(row, 5).toString());
        txt_NhanVienThanhToan.setText(myTable_HopDong_1Lan.getValueAt(row, 6).toString());
        txt_LoaiHopDong.setText(myTable_HopDong_1Lan.getValueAt(row, 7).toString());
        txt_MaKhachHang.setText(myTable_HopDong_1Lan.getValueAt(row, 8).toString());
        txt_HoKhachHang.setText(myTable_HopDong_1Lan.getValueAt(row, 9).toString());
        txt_TenKhachHang.setText(myTable_HopDong_1Lan.getValueAt(row, 10).toString());
        txt_DiaChi.setText(myTable_HopDong_1Lan.getValueAt(row, 11).toString());
        txt_SoDienThoai.setText(myTable_HopDong_1Lan.getValueAt(row, 12).toString());
        txt_SoChungMinh.setText(myTable_HopDong_1Lan.getValueAt(row, 13).toString());
        txt_MaXe.setText(myTable_HopDong_1Lan.getValueAt(row, 14).toString());

        String maXe = txt_MaXe.getText();

        if (maXe.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mã xe trống");
        } else {
            try {
                int MaXe = Integer.parseInt(maXe);
                ds_XeMay.docTimKiem_MaXeMay_TuBang_SQL(MaXe);
                ArrayList<XeMay> list = ds_XeMay.getDsXeMay();
                for (int i = 0; i < list.size(); i++) {
                    String HangXe = list.get(i).getHangXe();
                    String DongXe = list.get(i).getDongXe();
                    Float GiaXe = list.get(i).getGiaXe();
                    String giaXe = Float.toString(GiaXe);
                    int soLuong = list.get(i).getSoLuong();
                    txt_HangXe.setText(HangXe);
                    txt_DongXe.setText(DongXe);
                    txt_GiaXe.setText(giaXe);
                    txt_SoLuong.setText(Integer.toString(soLuong));

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txt_HangXe.setText(myTable_HopDong_1Lan.getValueAt(row, 15).toString());
        txt_DongXe.setText(myTable_HopDong_1Lan.getValueAt(row, 16).toString());

    }//GEN-LAST:event_myTable_HopDong_1LanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_SoLuongXeMuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoLuongXeMuaKeyPressed
        // TODO add your handling code here:
        txt_TongTien.setText("");
    }//GEN-LAST:event_txt_SoLuongXeMuaKeyPressed

    private void txt_GiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiamGiaKeyPressed
        // TODO add your handling code here:
        txt_TongTien.setText("");
    }//GEN-LAST:event_txt_GiamGiaKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new GUI_HopDong1Lan().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi_HopDong;
    private javax.swing.JButton btn_LayThongTin_KhachHang;
    private javax.swing.JButton btn_LayThongTin_XeMay;
    private javax.swing.JButton btn_PhatSinh_SoHopDong;
    private javax.swing.JButton btn_Them_HopDong_1Lan;
    private javax.swing.JButton btn_TinhTien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myTable_HopDong_1Lan;
    private javax.swing.JTextArea txt_DiaChi;
    private javax.swing.JTextField txt_DongXe;
    private javax.swing.JTextField txt_GiaXe;
    private javax.swing.JTextField txt_GiamGia;
    private javax.swing.JTextField txt_HangXe;
    private javax.swing.JTextField txt_HoKhachHang;
    private javax.swing.JTextField txt_LoaiHopDong;
    private javax.swing.JTextField txt_MaKhachHang;
    private javax.swing.JTextField txt_MaXe;
    private javax.swing.JTextField txt_NgayLapHopDong;
    private javax.swing.JTextField txt_NhanVienThanhToan;
    private javax.swing.JTextField txt_SoChungMinh;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_SoHopDong;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_SoLuongXeMua;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_ThoiGianBaoHanh;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables

    private void XoaTrang_HopDong_1Lan() {
        //To change body of generated methods, choose Tools | Templates.
        txt_SoHopDong.setText("");

        txt_ThoiGianBaoHanh.setText("");
        txt_TongTien.setText("");
        txt_SoLuongXeMua.setText("");
        txt_GiamGia.setText("0");
        txt_NhanVienThanhToan.setText("");

        txt_LoaiHopDong.setText("Một lần");
        txt_MaKhachHang.setText("");
        txt_HoKhachHang.setText("");
        txt_TenKhachHang.setText("");
        txt_DiaChi.setText("");
        txt_SoDienThoai.setText("");
        txt_SoChungMinh.setText("");
        txt_MaXe.setText("");
        txt_HangXe.setText("");
        txt_DongXe.setText("");
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String ngayLapHopDong = format.format(date);
        txt_NgayLapHopDong.setText(ngayLapHopDong);
        btn_Them_HopDong_1Lan.setEnabled(true);
        btn_TinhTien.setEnabled(true);
        btn_PhatSinh_SoHopDong.setEnabled(true);
        txt_GiaXe.setText("");
        txt_SoLuong.setText("");
    }

    private void LoadData_HopDong_1Lan() {
        //To change body of generated methods, choose Tools | Templates.
        ArrayList<HopDong1Lan> list = ds_HopDong_1Lan.getDsHopDong1Lan();

        for (int i = 0; i < list.size(); i++) {

            int soHopDong = list.get(i).getSoHopDong();
            String SoHopDong = Integer.toString(soHopDong);

            String ngayLapHopDong = list.get(i).getNgayLapHopDong();

            int thoiGianBaoHanh = list.get(i).getThoiGianBaoHanh();
            String ThoiGianBaoHanh = Integer.toString(thoiGianBaoHanh);
            float tongTien = list.get(i).getTongTien();
            String TongTien = Float.toString(tongTien);
            int soLuongXeMua = list.get(i).getSoLuongXeMua();
            String SoLuongXeMua = Integer.toString(soLuongXeMua);
            float giamGia = list.get(i).getGiamGia();
            String GiamGia = Float.toString(giamGia);
            String nhanVienThanhToan = list.get(i).getNhanVienThanhToan();
            String loaiHopDong = list.get(i).getLoaiHopDong();

            int MaKhachHang = list.get(i).getMaKhachHang();
            String maKhachHang = Integer.toString(MaKhachHang);
            String hoKhachHang = list.get(i).getHoKhachHang();
            String tenKhachHang = list.get(i).getTenKhachHang();
            String diaChi = list.get(i).getDiaChi();
            String soDienThoai = list.get(i).getSoDienThoai();
            String soChungMinh = list.get(i).getSoChungMinh();

            int maXe = list.get(i).getMaXe();
            String MaXe = Integer.toString(maXe);
            String hangXe = list.get(i).getHangXe();
            String dongXe = list.get(i).getDongXe();

            String rowData[] = {SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, SoLuongXeMua, GiamGia, nhanVienThanhToan, loaiHopDong, maKhachHang, hoKhachHang, tenKhachHang, diaChi, soDienThoai, soChungMinh, MaXe, hangXe, dongXe};
            DefaultTableModel TableModel = (DefaultTableModel) myTable_HopDong_1Lan.getModel();
            TableModel.addRow(rowData);

        }

        txt_HoKhachHang.setEnabled(false);
        txt_TenKhachHang.setEnabled(false);
        txt_DiaChi.setEnabled(false);
        txt_SoDienThoai.setEnabled(false);
        txt_SoChungMinh.setEnabled(false);
        txt_HangXe.setEnabled(false);
        txt_DongXe.setEnabled(false);
        txt_SoHopDong.setEnabled(false);
        txt_NgayLapHopDong.setEnabled(false);
        txt_LoaiHopDong.setEnabled(false);
        txt_TongTien.setEditable(false);
        txt_GiaXe.setEnabled(false);
        txt_SoLuong.setEnabled(false);
        txt_GiamGia.setText("0");
        txt_LoaiHopDong.setText("Một lần");
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String ngayLapHopDong = format.format(date);
        txt_NgayLapHopDong.setText(ngayLapHopDong);

    }

    private int KiemTraInput_HopDong() {
        //To change body of generated methods, choose Tools | Templates.
        if (!Pattern.matches("[0-9]+", txt_SoHopDong.getText())) {
            return 1;
        }
        if (!Pattern.matches("[0-9]+", txt_ThoiGianBaoHanh.getText())) {
            return 2;
        }
        if (!Pattern.matches("[0-9]+(.)[0-9]+", txt_TongTien.getText()) && !Pattern.matches("[0-9]+", txt_TongTien.getText())) {
            return 3;
        }
        if (!Pattern.matches("[0-9]+", txt_SoLuongXeMua.getText())) {
            return 4;
        }
        if (!Pattern.matches("[0-9]+", txt_GiamGia.getText())) {
            return 5;
        }
        if (!Pattern.matches("^[a-zA-Z\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_NhanVienThanhToan.getText())) {
            return 6;
        }
        if (!Pattern.matches("[0-9]{10,11}", txt_SoDienThoai.getText())) {
            return 7;
        }
        if (!Pattern.matches("^[a-zA-Z]+", txt_HangXe.getText())) {
            return 8;
        }

        return 0;
    }

}
