/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Hopdongs;

import QuanLiHopDong.DanhSach_HopDongTraGop;

import QuanLiHopDong.HopDongTraGop;
import QuanLiKhachHang.DanhSachKhachHang;
import QuanLiKhachHang.KhachHang;
import QuanLiXeMay.DanhSachXeMay;
import QuanLiXeMay.XeMay;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Dat
 */
public class GUI_HopDongTraGop extends javax.swing.JFrame {

    /**
     * Creates new form GUI_HopDongTraGop
     */
    private DanhSach_HopDongTraGop dsHopDong_TraGop;
    private DanhSachKhachHang ds_KhachHang;
    private DanhSachXeMay ds_XeMay;

    public GUI_HopDongTraGop() throws ClassNotFoundException {
        super("...::: Hợp đồng trả góp :::...");
        initComponents();
        dsHopDong_TraGop = new DanhSach_HopDongTraGop();
        dsHopDong_TraGop.docTuBang();

        ds_KhachHang = new DanhSachKhachHang();
        ds_XeMay = new DanhSachXeMay();

        LoadData_TraGop();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_SoHopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_NgayLapHopDong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ThoiGianBaoHanh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_SoTienThanhToan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_SoTienCon = new javax.swing.JTextField();
        txt_TongTien = new javax.swing.JTextField();
        combo_LanThanhToan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_NhanVienThanhToan = new javax.swing.JTextField();
        txt_LoaiHopDong = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_Lai = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_MaKhachHang = new javax.swing.JTextField();
        txt_HoKhachHang = new javax.swing.JTextField();
        txt_TenKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DiaChi = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_SoChungMinh = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_KhachHangTraHo = new javax.swing.JTextField();
        txt_SoChungMinh_KHTraHo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_MaXe = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_HangXe = new javax.swing.JTextField();
        txt_DongXe = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_GiaXe = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myTable_HopDongTraGop = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btn_PhatSinhSoHopDong = new javax.swing.JButton();
        btn_Them_HopDong = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_LayThongTin_KhachHang = new javax.swing.JButton();
        btn_LayThongTin_XeMay = new javax.swing.JButton();
        btn_TinhTongTien = new javax.swing.JButton();
        btn_TinhTienCon = new javax.swing.JButton();
        btn_TienCon = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin chi tiết hợp đồng - thanh toán trả góp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Hợp đồng :::..."));

        jLabel2.setText("Số hợp đồng");

        jLabel3.setText("Ngày lập HĐ");

        jLabel4.setText("Thời gian bảo hành (tháng)");

        jLabel5.setText("Tổng tiền (triệu)");

        jLabel6.setText("Lần thanh toán");

        jLabel7.setText("Số tiền thanh toán (triệu)");

        txt_SoTienThanhToan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_SoTienThanhToan.setForeground(new java.awt.Color(255, 0, 0));
        txt_SoTienThanhToan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SoTienThanhToanKeyPressed(evt);
            }
        });

        jLabel8.setText("Số tiền còn (triệu)");

        txt_SoTienCon.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_SoTienCon.setForeground(new java.awt.Color(255, 0, 0));

        txt_TongTien.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_TongTien.setForeground(new java.awt.Color(255, 0, 0));

        combo_LanThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lần 1", "Lần 2", "Lần 3" }));
        combo_LanThanhToan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_LanThanhToanItemStateChanged(evt);
            }
        });
        combo_LanThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_LanThanhToanActionPerformed(evt);
            }
        });

        jLabel9.setText("Nhân viên thanh toán");

        jLabel10.setText("Loại hợp đồng");

        jLabel23.setText("Lãi (%)");

        txt_Lai.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txt_Lai.setForeground(new java.awt.Color(0, 0, 0));
        txt_Lai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_LaiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_SoHopDong)
                    .addComponent(txt_NgayLapHopDong)
                    .addComponent(txt_ThoiGianBaoHanh)
                    .addComponent(txt_SoTienThanhToan)
                    .addComponent(txt_TongTien)
                    .addComponent(combo_LanThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_SoTienCon)
                    .addComponent(txt_NhanVienThanhToan)
                    .addComponent(txt_LoaiHopDong)
                    .addComponent(txt_Lai))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_SoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NgayLapHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_Lai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_LanThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_SoTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_SoTienCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_NhanVienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_LoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Khách hàng :::..."));

        jLabel11.setText("Mã khách hàng");

        jLabel12.setText("Họ khách hàng");

        jLabel13.setText("Tên khách hàng");

        jLabel14.setText("Địa chỉ");

        txt_MaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaKhachHangActionPerformed(evt);
            }
        });

        txt_DiaChi.setColumns(20);
        txt_DiaChi.setRows(5);
        jScrollPane1.setViewportView(txt_DiaChi);

        jLabel15.setText("Số điện thoại");

        jLabel16.setText("Số chứng minh");

        jLabel17.setText("Khách hàng trả hộ");

        jLabel18.setText("Số chứng minh KH trả hộ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaKhachHang)
                    .addComponent(txt_HoKhachHang)
                    .addComponent(txt_TenKhachHang)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txt_SoDienThoai)
                    .addComponent(txt_SoChungMinh)
                    .addComponent(txt_SoChungMinh_KHTraHo)
                    .addComponent(txt_KhachHangTraHo))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_HoKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_SoChungMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_KhachHangTraHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_SoChungMinh_KHTraHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Xe máy :::..."));

        jLabel19.setText("Mã xe");

        jLabel20.setText("Hãng xe");

        jLabel21.setText("Dòng xe");

        jLabel22.setText("Giá mỗi chiếc (triệu)");

        txt_GiaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaXeActionPerformed(evt);
            }
        });
        txt_GiaXe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_GiaXeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaXe, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_HangXe)
                    .addComponent(txt_DongXe)
                    .addComponent(txt_GiaXe))
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_MaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_HangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_DongXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_GiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 173, Short.MAX_VALUE))
        );

        myTable_HopDongTraGop.setAutoCreateRowSorter(true);
        myTable_HopDongTraGop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hợp đồng", "Ngày lập HĐ", "Thời gian bảo hành", "Tổng tiền ", "Lần thanh toán", "Số tiền thanh toán", "Số tiền còn", "Nhân viên thanh toán", "Loại hợp đồng", "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Số chứng minh", "Khách hàng trả hộ", "Số chứng minh KH trả hộ", "Mã xe", "Hãng", "Dòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable_HopDongTraGop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTable_HopDongTraGopMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myTable_HopDongTraGop);

        btn_PhatSinhSoHopDong.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:create.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_PhatSinhSoHopDong.setText("Phát sinh số hợp đồng");
        btn_PhatSinhSoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhatSinhSoHopDongActionPerformed(evt);
            }
        });

        btn_Them_HopDong.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:add.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Them_HopDong.setText("Thêm");
        btn_Them_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them_HopDongActionPerformed(evt);
            }
        });

        btn_LamMoi.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:renew.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_LayThongTin_KhachHang.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:customer.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LayThongTin_KhachHang.setText("Lấy thông tin khách hàng");
        btn_LayThongTin_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LayThongTin_KhachHangActionPerformed(evt);
            }
        });

        btn_LayThongTin_XeMay.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:motorbike.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_LayThongTin_XeMay.setText("Lấy thông tin xe máy");
        btn_LayThongTin_XeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LayThongTin_XeMayActionPerformed(evt);
            }
        });

        btn_TinhTongTien.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:sum.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_TinhTongTien.setText("Tính tổng tiền");
        btn_TinhTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTongTienActionPerformed(evt);
            }
        });

        btn_TinhTienCon.setText("Tính tiền còn");
        btn_TinhTienCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTienConActionPerformed(evt);
            }
        });

        btn_TienCon.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:remove.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_TienCon.setText("Tính tiền còn");
        btn_TienCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TienConActionPerformed(evt);
            }
        });

        btn_Huy.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Huy.setText("Thoát");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_PhatSinhSoHopDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Them_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TinhTongTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TienCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LayThongTin_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btn_TinhTienCon))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_LayThongTin_XeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_PhatSinhSoHopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them_HopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TinhTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TienCon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LayThongTin_KhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LayThongTin_XeMay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TinhTienCon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(153, 153, 153))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaKhachHangActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_Them_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them_HopDongActionPerformed
        // TODO add your handling code here:
        if (KiemTraInput_HopDong() == 0) {

            try {
                int row = myTable_HopDongTraGop.getSelectedRow();
                String soHopDong = txt_SoHopDong.getText();
                int SoHopDong = Integer.parseInt(soHopDong);
                int index = combo_LanThanhToan.getSelectedIndex();
                String lanThanhToan = combo_LanThanhToan.getItemAt(index);
                String soHopDong_TuBang = myTable_HopDongTraGop.getValueAt(row, 0).toString();
                String lanThanhToan_TuBang = myTable_HopDongTraGop.getValueAt(row, 4).toString();
                if (soHopDong.equalsIgnoreCase(soHopDong_TuBang) && lanThanhToan.equalsIgnoreCase(lanThanhToan_TuBang)) {
                    JOptionPane.showMessageDialog(this, "Chọn lần thanh toán khác vì hợp đồng này đã thanh toán " + lanThanhToan);
                } else {
                    String ngayLapHopDong = txt_NgayLapHopDong.getText();
                    String thoiGianBaoHanh = txt_ThoiGianBaoHanh.getText();
                    int ThoiGianBaoHanh = Integer.parseInt(thoiGianBaoHanh);
                    String tongTien = txt_TongTien.getText();
                    float TongTien = Float.parseFloat(tongTien);

                    String soTienThanhToan = txt_SoTienThanhToan.getText();
                    float SoTienThanhToan = Float.parseFloat(soTienThanhToan);
                    String soTienCon = txt_SoTienCon.getText();
                    float SoTienCon = Float.parseFloat(soTienCon);
                    String nhanVienThanhToan = txt_NhanVienThanhToan.getText();
                    String loaiHopDong = txt_LoaiHopDong.getText();

                    String maKhachHang = txt_MaKhachHang.getText();
                    int MaKhachHang = Integer.parseInt(maKhachHang);
                    String HoKhachHang = txt_HoKhachHang.getText();
                    String TenKhachHang = txt_TenKhachHang.getText();
                    String DiaChi = txt_DiaChi.getText();
                    String SoDienThoai = txt_SoDienThoai.getText();
                    String SoChungMinh = txt_SoChungMinh.getText();
                    String khachHangTraHo = txt_KhachHangTraHo.getText();
                    String soChungMinh_KHTraHo = txt_SoChungMinh_KHTraHo.getText();
                    String maXe = txt_MaXe.getText();
                    int MaXe = Integer.parseInt(maXe);
                    String HangXe = txt_HangXe.getText();
                    String DongXe = txt_DongXe.getText();

                    HopDongTraGop hd = new HopDongTraGop(SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, lanThanhToan, SoTienThanhToan, SoTienCon, nhanVienThanhToan, loaiHopDong, MaKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, khachHangTraHo, soChungMinh_KHTraHo, MaXe, HangXe, DongXe);
                    if (dsHopDong_TraGop.Them_HopDong_1Lan(hd)) {
                        String row_Data[] = {soHopDong, ngayLapHopDong, thoiGianBaoHanh, tongTien, lanThanhToan, soTienThanhToan, soTienCon, nhanVienThanhToan, loaiHopDong, maKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, khachHangTraHo, soChungMinh_KHTraHo, maXe, HangXe, DongXe};
                        DefaultTableModel table_Model = (DefaultTableModel) myTable_HopDongTraGop.getModel();
                        table_Model.addRow(row_Data);
                        dsHopDong_TraGop.ThemHopDong_SQL(SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, lanThanhToan, SoTienThanhToan, SoTienCon, nhanVienThanhToan, loaiHopDong, MaKhachHang, HoKhachHang, TenKhachHang, DiaChi, SoDienThoai, SoChungMinh, khachHangTraHo, soChungMinh_KHTraHo, MaXe, HangXe, DongXe);
                        JOptionPane.showMessageDialog(this, "Thêm thành công!");
                        XoaTrang_HopDong_TraGop();

                    }
                }

//               
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            switch (KiemTraInput_HopDong()) {
                case 1: {
                    JOptionPane.showMessageDialog(this, "Hãy phát sinh số hợp đồng!");
                    break;
                }
                case 2: {
                    JOptionPane.showMessageDialog(this, "Nhập thời gian bảo hành là số nguyên dương\n Ví dụ: 12");
                    break;
                }
                case 3: {
                    JOptionPane.showMessageDialog(this, "Tổng tiền trống.");
                    break;
                }
                case 4: {
                    JOptionPane.showMessageDialog(this, "Nhập số tiền thanh toán là một số thực. Ví dụ: 12.4");
                    break;
                }
                case 5: {
                    JOptionPane.showMessageDialog(this, "Số tiền còn trống!");
                    break;
                }
                case 6: {
                    JOptionPane.showMessageDialog(this, "Nhập nhân viên thanh toán là chuỗi kí tự \n Ví dụ: Nguyễn Thị Hồng ");
                    break;
                }
                case 7: {
                    JOptionPane.showMessageDialog(this, "Yêu cầu lấy thông tin khách hàng. \n Ví dụ: 23 ");
                    break;
                }
                case 8: {
                    JOptionPane.showMessageDialog(this, "Yêu cầu lấy thông tin xe!");
                    break;
                }
                case 9: {
                    JOptionPane.showMessageDialog(this, "Nhập họ tên khách hàng trả hộ!");
                    break;
                }
                case 10: {
                    JOptionPane.showMessageDialog(this, "Nhập số chứng minh của khách hàng trả hộ");
                    break;
                }

            }
        }
    }//GEN-LAST:event_btn_Them_HopDongActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        XoaTrang_HopDong_TraGop();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_PhatSinhSoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhatSinhSoHopDongActionPerformed
        // TODO add your handling code here:
        Random rs = new Random();
        int so = rs.nextInt(1000000);
        txt_SoHopDong.setText(Integer.toString(so));
    }//GEN-LAST:event_btn_PhatSinhSoHopDongActionPerformed

    private void btn_LayThongTin_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LayThongTin_KhachHangActionPerformed
        // TODO add your handling code here:
        String maKhachHang = txt_MaKhachHang.getText();
        if (maKhachHang.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng trống!");
        } else {
            try {
                ds_KhachHang.docTimKiem_MaKhachHang_SQL(Integer.parseInt(maKhachHang));
                ArrayList<KhachHang> list = ds_KhachHang.getDsKhachHang();
                for (int i = 0; i < list.size(); i++) {

                    String HoKhachHang = list.get(i).getHoKhachHang();
                    String TenKhachHang = list.get(i).getTenKhachHang();
                    String DiaChi = list.get(i).getDiaChiKhachHang();
                    String SoDienThoai = list.get(i).getSoDienThoaiKhachHang();
                    String SoChungMinh = list.get(i).getSoChungMinhKhachHang();

                    txt_HoKhachHang.setText(HoKhachHang);
                    txt_TenKhachHang.setText(TenKhachHang);
                    txt_DiaChi.setText(DiaChi);
                    txt_SoDienThoai.setText(SoDienThoai);
                    txt_SoChungMinh.setText(SoChungMinh);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_LayThongTin_KhachHangActionPerformed

    private void btn_LayThongTin_XeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LayThongTin_XeMayActionPerformed
        // TODO add your handling code here:
        String maXe = txt_MaXe.getText();

        if (maXe.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mã xe trống");
        } else {
            try {
                int MaXe = Integer.parseInt(maXe);
                ds_XeMay.docTimKiem_MaXeMay_TuBang_SQL(MaXe);
                ArrayList<XeMay> list = ds_XeMay.getDsXeMay();
                for (int i = 0; i < list.size(); i++) {
                    String HangXe = list.get(i).getHangXe();
                    String DongXe = list.get(i).getDongXe();
                    float GiaXe = list.get(i).getGiaXe();
                    String giaXe = Float.toString(GiaXe);
                    txt_HangXe.setText(HangXe);
                    txt_DongXe.setText(DongXe);
                    txt_GiaXe.setText(giaXe);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_LayThongTin_XeMayActionPerformed

    private void txt_GiaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaXeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_GiaXeActionPerformed

    private void txt_GiaXeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiaXeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_GiaXeKeyPressed

    private void btn_TinhTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTongTienActionPerformed
        // TODO add your handling code here:t
        String giaXe = txt_GiaXe.getText();

        String laiSuat = txt_Lai.getText();
        if (laiSuat.equals("") || giaXe.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa lấy thông tin xe hoặc chưa nhập lãi");
        } else {
            try {
                float GiaXe = Float.parseFloat(giaXe);
                float lai = Float.parseFloat(laiSuat);
                float TongTien = GiaXe + GiaXe * lai / 100;
                String tongTien = Float.toString(TongTien);
                txt_TongTien.setText(tongTien);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Nhập lãi suất là một số thực. Ví dụ: 0.9");
            }
        }
    }//GEN-LAST:event_btn_TinhTongTienActionPerformed

    private void btn_TinhTienConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTienConActionPerformed
        // TODO add your handling code here:
        btn_Them_HopDong.setEnabled(true);
        String TongTien = txt_TongTien.getText();
        String SoTienThanhToan = txt_SoTienThanhToan.getText();

        String index = (String) combo_LanThanhToan.getSelectedItem();
//        int index = combo_LanThanhToan.getSelectedItem
        if (index.equalsIgnoreCase("Lần 1")) {
            if (TongTien.equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa có tổng tiền");
            } else {
                try {
                    float tongTien = Float.parseFloat(TongTien);
                    float soTienThanhToan = Float.parseFloat(SoTienThanhToan);
                    float soTienCon = tongTien - soTienThanhToan;
                    String SoTienCon = Float.toString(soTienCon);
                    txt_SoTienCon.setText(SoTienCon);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Nhập số tiền thanh toán là một số thực hoặc số nguyên.\n Ví dụ: 12.5");
                }

            }
        }
        if (index.equalsIgnoreCase("Lần 2")) {
            try {
                int row = myTable_HopDongTraGop.getSelectedRow();
                String soTienCon = myTable_HopDongTraGop.getValueAt(row, 6).toString();
                float SoTienCon = Float.parseFloat(soTienCon);

                float soTienThanhToan = Float.parseFloat(SoTienThanhToan);
                float tienConLan2 = SoTienCon - soTienThanhToan;
                String TienConLan2 = Float.toString(tienConLan2);
                txt_SoTienCon.setText(TienConLan2);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (index.equalsIgnoreCase("Lần 3")) {
            try {
                int row = myTable_HopDongTraGop.getSelectedRow();
                String soTienCon = myTable_HopDongTraGop.getValueAt(row, 6).toString();
                float SoTienCon = Float.parseFloat(soTienCon);

                float soTienThanhToan = Float.parseFloat(SoTienThanhToan);
                float tienConLan3 = SoTienCon - soTienThanhToan;
                if (tienConLan3 > 0) {
                    JOptionPane.showMessageDialog(this, "Thanh toán lần 3 bắt buộc phải trả hết tiền xe máy!\n Hãy thông báo cho khách hàng biết!");
                } else {
                    String TienConLan3 = Float.toString(tienConLan3);
                    txt_SoTienCon.setText(TienConLan3);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_TinhTienConActionPerformed

    private void myTable_HopDongTraGopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTable_HopDongTraGopMouseClicked
        // TODO add your handling code here:
        txt_Lai.setEnabled(false);
        btn_TienCon.setEnabled(true);
        btn_PhatSinhSoHopDong.setEnabled(false);
        btn_LayThongTin_KhachHang.setEnabled(false);
        btn_LayThongTin_XeMay.setEnabled(false);
        int row = myTable_HopDongTraGop.getSelectedRow();
        txt_SoHopDong.setText(myTable_HopDongTraGop.getValueAt(row, 0).toString());
        txt_NgayLapHopDong.setText(myTable_HopDongTraGop.getValueAt(row, 1).toString());
        txt_ThoiGianBaoHanh.setText(myTable_HopDongTraGop.getValueAt(row, 2).toString());
        txt_TongTien.setText(myTable_HopDongTraGop.getValueAt(row, 3).toString());
        txt_MaXe.setText(myTable_HopDongTraGop.getValueAt(row, 17).toString());
        String maXe = txt_MaXe.getText();

        if (maXe.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mã xe trống");
        } else {
            try {
                int MaXe = Integer.parseInt(maXe);
                ds_XeMay.docTimKiem_MaXeMay_TuBang_SQL(MaXe);
                ArrayList<XeMay> list = ds_XeMay.getDsXeMay();
                for (int i = 0; i < list.size(); i++) {
                    String HangXe = list.get(i).getHangXe();
                    String DongXe = list.get(i).getDongXe();
                    Float GiaXe = list.get(i).getGiaXe();
                    String giaXe = Float.toString(GiaXe);
                    txt_HangXe.setText(HangXe);
                    txt_DongXe.setText(DongXe);
                    txt_GiaXe.setText(giaXe);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_HopDong1Lan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        String tongTien = txt_TongTien.getText();
        float TongTien = Float.parseFloat(tongTien);
        String giaXe = txt_GiaXe.getText();
        float GiaXe = Float.parseFloat(giaXe);
        float lai = (TongTien - GiaXe) / GiaXe * 100;
        String Lai = Float.toString(lai);
        txt_Lai.setText(Lai);

        String lanThanhToan = myTable_HopDongTraGop.getValueAt(row, 4).toString();
        if (lanThanhToan.equalsIgnoreCase("Lần 1")) {
            combo_LanThanhToan.removeAllItems();
            combo_LanThanhToan.addItem("Lần 1");
            combo_LanThanhToan.addItem("Lần 2");
            combo_LanThanhToan.addItem("Lần 3");
            combo_LanThanhToan.setSelectedIndex(0);
            txt_SoTienCon.setText("");
            btn_Them_HopDong.setEnabled(true);

        }
        if (lanThanhToan.equalsIgnoreCase("Lần 2")) {
            combo_LanThanhToan.removeAllItems();
            combo_LanThanhToan.addItem("Lần 2");
            combo_LanThanhToan.addItem("Lần 3");
            combo_LanThanhToan.setSelectedIndex(0);
            txt_SoTienCon.setText("");
            btn_Them_HopDong.setEnabled(true);
        }
        if (lanThanhToan.equalsIgnoreCase("Lần 3")) {
            combo_LanThanhToan.removeAllItems();
            combo_LanThanhToan.addItem("Lần 3");
            combo_LanThanhToan.setSelectedIndex(0);
            btn_Them_HopDong.setEnabled(false);

        }

        txt_SoTienThanhToan.setText(myTable_HopDongTraGop.getValueAt(row, 5).toString());

        txt_SoTienCon.setText(myTable_HopDongTraGop.getValueAt(row, 6).toString());

        txt_NhanVienThanhToan.setText(myTable_HopDongTraGop.getValueAt(row, 7).toString());
        txt_LoaiHopDong.setText(myTable_HopDongTraGop.getValueAt(row, 8).toString());
        txt_MaKhachHang.setText(myTable_HopDongTraGop.getValueAt(row, 9).toString());
        txt_HoKhachHang.setText(myTable_HopDongTraGop.getValueAt(row, 10).toString());
        txt_TenKhachHang.setText(myTable_HopDongTraGop.getValueAt(row, 11).toString());
        txt_DiaChi.setText(myTable_HopDongTraGop.getValueAt(row, 12).toString());
        txt_SoDienThoai.setText(myTable_HopDongTraGop.getValueAt(row, 13).toString());
        txt_SoChungMinh.setText(myTable_HopDongTraGop.getValueAt(row, 14).toString());
        txt_KhachHangTraHo.setText(myTable_HopDongTraGop.getValueAt(row, 15).toString());
        txt_SoChungMinh_KHTraHo.setText(myTable_HopDongTraGop.getValueAt(row, 16).toString());

        txt_HangXe.setText(myTable_HopDongTraGop.getValueAt(row, 18).toString());
        txt_DongXe.setText(myTable_HopDongTraGop.getValueAt(row, 19).toString());
    }//GEN-LAST:event_myTable_HopDongTraGopMouseClicked

    private void combo_LanThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_LanThanhToanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_combo_LanThanhToanActionPerformed

    private void btn_TienConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TienConActionPerformed
        // TODO add your handling code here:
        int row = myTable_HopDongTraGop.getSelectedRow();
        String LanThanhToan = (String) combo_LanThanhToan.getSelectedItem();
        String tongTien = txt_TongTien.getText();
        String soTienThanhToan = txt_SoTienThanhToan.getText();
        String TienCon = txt_SoTienCon.getText();
        String TienCon_TuBang = myTable_HopDongTraGop.getValueAt(row, 6).toString();

        if (LanThanhToan.equalsIgnoreCase("Lần 1")) {
            try {
                float TongTien = Float.parseFloat(tongTien);
                float SoTienThanhToan = Float.parseFloat(soTienThanhToan);
                float SoTienCon = TongTien - SoTienThanhToan;
                if (SoTienCon < 0) {
                    JOptionPane.showMessageDialog(this, "Số tiền còn phải lớn hơn hoặc bằng 0");
                } else {
                    String soTienCon = Float.toString(SoTienCon);
                    txt_SoTienCon.setText(soTienCon);
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Yêu cầu tính Tính tổng tiền và nhập số tiền thanh toán.");
            }
        }
        if (LanThanhToan.equalsIgnoreCase("Lần 2")) {
            try {
                float SoTienCon = Float.parseFloat(TienCon_TuBang);
                float SoTienThanhToan = Float.parseFloat(soTienThanhToan);
                float SoTienCon2 = SoTienCon - SoTienThanhToan;
                if (SoTienCon2 < 0) {
                    JOptionPane.showMessageDialog(this, "Số tiền còn phải lớn hơn hoặc bằng 0");
                } else {
                    String soTienCon = Float.toString(SoTienCon2);
                    txt_SoTienCon.setText(soTienCon);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (LanThanhToan.equalsIgnoreCase("Lần 3")) {
            try {
                float SoTienCon = Float.parseFloat(TienCon_TuBang);
                float SoTienThanhToan = Float.parseFloat(soTienThanhToan);
                float SoTienCon2 = SoTienCon - SoTienThanhToan;
                if (SoTienCon2 < 0) {
                    JOptionPane.showMessageDialog(this, "Số tiền còn phải lớn hơn hoặc bằng 0");
                } else if (SoTienCon2 > 0) {
                    JOptionPane.showMessageDialog(this, "Yêu cầu khách hàng thanh toán lần 3 phải trả hết số tiền còn!\n Thông báo cho khách hàng biết.");
                } else {
                    String soTienCon = Float.toString(SoTienCon2);
                    txt_SoTienCon.setText(soTienCon);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_TienConActionPerformed

    private void txt_LaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LaiKeyPressed
        // TODO add your handling code here:
        txt_TongTien.setText("");
    }//GEN-LAST:event_txt_LaiKeyPressed

    private void combo_LanThanhToanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_LanThanhToanItemStateChanged
        // TODO add your handling code here:
        txt_SoTienCon.setText("");
        txt_SoTienThanhToan.setText("");
    }//GEN-LAST:event_combo_LanThanhToanItemStateChanged

    private void txt_SoTienThanhToanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoTienThanhToanKeyPressed
        // TODO add your handling code here:_
        txt_SoTienCon.setText("");
    }//GEN-LAST:event_txt_SoTienThanhToanKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDongTraGop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDongTraGop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDongTraGop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_HopDongTraGop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new GUI_HopDongTraGop().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(GUI_HopDongTraGop.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_LayThongTin_KhachHang;
    private javax.swing.JButton btn_LayThongTin_XeMay;
    private javax.swing.JButton btn_PhatSinhSoHopDong;
    private javax.swing.JButton btn_Them_HopDong;
    private javax.swing.JButton btn_TienCon;
    private javax.swing.JButton btn_TinhTienCon;
    private javax.swing.JButton btn_TinhTongTien;
    private javax.swing.JComboBox<String> combo_LanThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myTable_HopDongTraGop;
    private javax.swing.JTextArea txt_DiaChi;
    private javax.swing.JTextField txt_DongXe;
    private javax.swing.JTextField txt_GiaXe;
    private javax.swing.JTextField txt_HangXe;
    private javax.swing.JTextField txt_HoKhachHang;
    private javax.swing.JTextField txt_KhachHangTraHo;
    private javax.swing.JTextField txt_Lai;
    private javax.swing.JTextField txt_LoaiHopDong;
    private javax.swing.JTextField txt_MaKhachHang;
    private javax.swing.JTextField txt_MaXe;
    private javax.swing.JTextField txt_NgayLapHopDong;
    private javax.swing.JTextField txt_NhanVienThanhToan;
    private javax.swing.JTextField txt_SoChungMinh;
    private javax.swing.JTextField txt_SoChungMinh_KHTraHo;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_SoHopDong;
    private javax.swing.JTextField txt_SoTienCon;
    private javax.swing.JTextField txt_SoTienThanhToan;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_ThoiGianBaoHanh;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables

    private void LoadData_TraGop() {
        ArrayList<HopDongTraGop> list = dsHopDong_TraGop.getDsHopDongTraGop();

        for (int i = 0; i < list.size(); i++) {

            int soHopDong = list.get(i).getSoHopDong();
            String SoHopDong = Integer.toString(soHopDong);

            String ngayLapHopDong = list.get(i).getNgayLapHopDong();

            int thoiGianBaoHanh = list.get(i).getThoiGianBaoHanh();
            String ThoiGianBaoHanh = Integer.toString(thoiGianBaoHanh);
            float tongTien = list.get(i).getTongTien();
            String TongTien = Float.toString(tongTien);

            String lanThanhToan = list.get(i).getLanThanhToan();
            float soTienThanhToan = list.get(i).getSoTienThanhToan();
            String SoTienThanhToan = Float.toString(soTienThanhToan);
            float soTienCon = list.get(i).getSoTienCon();
            String SoTienCon = Float.toString(soTienCon);
            String nhanVienThanhToan = list.get(i).getNhanVienThanhToan();
            String loaiHopDong = list.get(i).getLoaiHopDong();

            int MaKhachHang = list.get(i).getMaKhachHang();
            String maKhachHang = Integer.toString(MaKhachHang);
            String hoKhachHang = list.get(i).getHoKhachHang();
            String tenKhachHang = list.get(i).getTenKhachHang();
            String diaChi = list.get(i).getDiaChi();
            String soDienThoai = list.get(i).getSoDienThoai();
            String soChungMinh = list.get(i).getSoChungMinh();
            String khachHangTraHo = list.get(i).getKhachHangThanhToanHo();
            String soChungMinh_KHTraHo = list.get(i).getSoChungMinh_KhachHangThanhToanHo();

            int maXe = list.get(i).getMaXe();
            String MaXe = Integer.toString(maXe);
            String hangXe = list.get(i).getHangXe();
            String dongXe = list.get(i).getDongXe();
            String rowData[] = {SoHopDong, ngayLapHopDong, ThoiGianBaoHanh, TongTien, lanThanhToan, SoTienThanhToan, SoTienCon, nhanVienThanhToan, loaiHopDong, maKhachHang, hoKhachHang, tenKhachHang, diaChi, soDienThoai, soChungMinh, khachHangTraHo, soChungMinh_KHTraHo, MaXe, hangXe, dongXe};

            DefaultTableModel TableModel = (DefaultTableModel) myTable_HopDongTraGop.getModel();
            TableModel.addRow(rowData);

        }
        txt_HoKhachHang.setEnabled(false);
        txt_TenKhachHang.setEnabled(false);
        txt_DiaChi.setEnabled(false);
        txt_SoDienThoai.setEnabled(false);
        txt_SoChungMinh.setEnabled(false);
        txt_HangXe.setEnabled(false);
        txt_DongXe.setEnabled(false);
        txt_SoHopDong.setEnabled(false);
        txt_NgayLapHopDong.setEnabled(false);
        txt_LoaiHopDong.setEnabled(false);
        txt_TongTien.setEditable(false);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String ngayLapHopDong = format.format(date);
        txt_NgayLapHopDong.setText(ngayLapHopDong);
        txt_LoaiHopDong.setText("Trả góp");
        txt_GiaXe.setText("");
        txt_SoTienCon.setEditable(false);
        txt_GiaXe.setEnabled(false);

//        txt_GiaXe.setEnabled(false);
//To change body of generated methods, choose Tools | Templates.
    }

    private int KiemTraInput_HopDong() {
        //To change body of generated methods, choose Tools | Templates.
        if (!Pattern.matches("[0-9]+", txt_SoHopDong.getText())) {
            return 1;
        }
        if (!Pattern.matches("[0-9]+", txt_ThoiGianBaoHanh.getText())) {
            return 2;
        }
        if (!Pattern.matches("[0-9]+(.)[0-9]+", txt_TongTien.getText()) && !Pattern.matches("[0-9]+", txt_TongTien.getText())) {
            return 3;
        }

        if (!Pattern.matches("[0-9]+(.)[0-9]+", txt_SoTienThanhToan.getText()) && !Pattern.matches("[0-9]+", txt_SoTienThanhToan.getText())) {
            return 4;
        }
        if (!Pattern.matches("[0-9]+(.)[0-9]+", txt_SoTienCon.getText()) && !Pattern.matches("[0-9]+", txt_SoTienCon.getText())) {
            return 5;
        }

        if (!Pattern.matches("^[a-zA-Z\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_NhanVienThanhToan.getText())) {
            return 6;
        }
        if (!Pattern.matches("[0-9]{10,11}", txt_SoDienThoai.getText())) {
            return 7;
        }
        if (!Pattern.matches("^[a-zA-Z]+", txt_HangXe.getText())) {
            return 8;
        }
        if (!Pattern.matches("^[a-zA-Z\\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,100}", txt_KhachHangTraHo.getText())) {
            return 9;
        }
        if (!Pattern.matches("^[0-9]+", txt_SoChungMinh_KHTraHo.getText())) {
            return 10;
        }

        return 0;
    }

    private void XoaTrang_HopDong_TraGop() {
        //To change body of generated methods, choose Tools | Templates.
        txt_SoHopDong.setText("");
        txt_NgayLapHopDong.setText("");
        txt_ThoiGianBaoHanh.setText("");
        txt_TongTien.setText("");
        combo_LanThanhToan.setSelectedIndex(0);
        txt_SoTienThanhToan.setText("");
        txt_Lai.setText("");
        txt_SoTienCon.setText("");
        txt_NhanVienThanhToan.setText("");
        txt_LoaiHopDong.setText("Trả góp");

        txt_MaKhachHang.setText("");
        txt_HoKhachHang.setText("");
        txt_TenKhachHang.setText("");
        txt_DiaChi.setText("");
        txt_SoDienThoai.setText("");
        txt_SoChungMinh.setText("");
        txt_KhachHangTraHo.setText("");
        txt_SoChungMinh_KHTraHo.setText("");

        txt_MaXe.setText("");
        txt_HangXe.setText("");
        txt_DongXe.setText("");
        txt_GiaXe.setText("");

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String ngayLapHopDong = format.format(date);
        txt_NgayLapHopDong.setText(ngayLapHopDong);
        btn_Them_HopDong.setEnabled(true);
        btn_LayThongTin_KhachHang.setEnabled(true);
        btn_LayThongTin_XeMay.setEnabled(true);
    }
}
