/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_QuanLi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Dat
 */
public class GUI_LichSuKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_LichSuKhachHang
     */
    public GUI_LichSuKhachHang() {
        super("...::: Lịch sử mua bán xe máy :::....");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable_1Lan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myTable_TraGop = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaKhachHang = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("....::: Hợp đồng thanh toán 1 lần :::..."));

        myTable_1Lan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Số chứng minh", "Số hợp đồng", "Ngày lập HĐ", "Tổng tiền", "Thời gian bảo hành", "Mã xe", "Hãng", "Dòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myTable_1Lan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("...::: Hợp đồng trả góp :::..."));

        myTable_TraGop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Số chứng minh", "Số hợp đồng", "Ngày lập HĐ", "Tổng tiền", "Thời gian bảo hành", "Lần thanh toán", "Số tiền còn", "Khách hàng thanh toán hộ", "Mã xe", "Hãng xe", "Dòng xe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(myTable_TraGop);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel2.setText("Mã khách hàng:");

        btn_Tim.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:search.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Tim.setText("Tìm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        btn_Thoat.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:huy.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lịch sử giao dịch của khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:

        String maKhachHang = txt_MaKhachHang.getText();
        int MaKhachHang = Integer.parseInt(maKhachHang);
        DefaultTableModel table_Model1 = (DefaultTableModel) myTable_1Lan.getModel();
        table_Model1.setRowCount(0);
         DefaultTableModel table_Model2 = (DefaultTableModel) myTable_TraGop.getModel();
        table_Model2.setRowCount(0);
        if (maKhachHang.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã khách hàng để tìm kiếm");
        } else {
            try {
                Connection con = null;

                ResultSet rs = null;
                PreparedStatement prsttm1 = null;
                PreparedStatement prsttm2 = null;
                String connectionUrl = "jdbc:sqlserver://localhost:1433;" + "databaseName=quanli;user=sa;password=123";

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                con = DriverManager.getConnection(connectionUrl);

                String sql1 = "select kh.makhachhang,kh.hokhachhang,kh.tenkhachhang, kh.sochungminh, hd.sohopdong,hd.ngaylaphopdong,hd.tongtien, hd.thoigianbaohanh,hd.maxe, hd.hang,hd.dongxe \n"
                        + " from khachhang kh inner join HopDong1Lan hd on kh.makhachhang = hd.makhachhang\n"
                        + " where kh.makhachhang = ?";

                prsttm1 = con.prepareStatement(sql1);
                prsttm1.setInt(1, MaKhachHang);
                rs = prsttm1.executeQuery();
                while (rs.next()) {

                    int maKH = rs.getInt(1);
                    String maKH_ChuyenDoi = Integer.toString(maKH);
                    String hoKhachHang = rs.getString(2);
                    String tenKhachHang = rs.getString(3);
                    String soChungMinh = rs.getString(4);
                    int soHopDong = rs.getInt(5);
                    String soHopDong_ChuyenDoi = Integer.toString(soHopDong);
                    String ngayLapHopDong = rs.getString(6);
                    float tongTien = rs.getFloat(7);
                    String TongTien_ChuyenDoi = Double.toString(tongTien);
                    int thoiGianBaoHanh = rs.getInt(8);
                    String thoiGian = Integer.toString(thoiGianBaoHanh);
                    int maXe = rs.getInt(9);
                    String maXe_ChuyenDoi = Integer.toString(maXe);
                    String hang = rs.getString(10);
                    String dong = rs.getString(11);

                    String row_Data[] = {maKH_ChuyenDoi, hoKhachHang, tenKhachHang, soChungMinh, soHopDong_ChuyenDoi, ngayLapHopDong, TongTien_ChuyenDoi, thoiGian, maXe_ChuyenDoi, hang, dong};
                    table_Model1.addRow(row_Data);

                }
                String sql2 = "select kh.makhachhang,kh.hokhachhang,kh.tenkhachhang, "
                        + "kh.sochungminh, hd.sohopdong,hd.ngaylaphopdong, "
                        + "hd.tongtien, hd.thoigianbaohanh,hd.lanthanhtoan,"
                        + "hd.sotiencon, hd.khachhangthanhtoanho,hd.maxe, hd.hang,hd.dongxe \n"
                        + " from khachhang kh inner join HopDongTraGop hd on kh.makhachhang = hd.makhachhang\n"
                        + "where kh.makhachhang = ?";

                prsttm2 = con.prepareStatement(sql2);
                prsttm2.setInt(1, MaKhachHang);
                rs = prsttm2.executeQuery();
                while (rs.next()) {

                    int maKH = rs.getInt(1);
                    String maKH_ChuyenDoi = Integer.toString(maKH);
                    String hoKhachHang = rs.getString(2);
                    String tenKhachHang = rs.getString(3);
                    String soChungMinh = rs.getString(4);
                    int soHopDong = rs.getInt(5);
                    String soHopDong_ChuyenDoi = Integer.toString(soHopDong);
                    String ngayLapHopDong = rs.getString(6);
                    float tongTien = rs.getFloat(7);
                    String TongTien_ChuyenDoi = Double.toString(tongTien);
                    int thoiGianBaoHanh = rs.getInt(8);
                    String thoiGian = Integer.toString(thoiGianBaoHanh);
                   
                    String lanThanhToan = rs.getString(9);
                    float soTienCon = rs.getFloat(10);
                    String SoTienCon = Float.toString(soTienCon);
                    String khachHangThanhToanHo = rs.getString(11);
                     int maXe = rs.getInt(12);
                    String maXe_ChuyenDoi = Integer.toString(maXe);
                    String hang = rs.getString(13);
                    String dong = rs.getString(14);

                    String row_Data[] = {maKH_ChuyenDoi, hoKhachHang, tenKhachHang, soChungMinh, soHopDong_ChuyenDoi, ngayLapHopDong, TongTien_ChuyenDoi, thoiGian,lanThanhToan,SoTienCon,khachHangThanhToanHo, maXe_ChuyenDoi, hang, dong};
                    table_Model2.addRow(row_Data);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        txt_MaKhachHang.setText("");

    }//GEN-LAST:event_btn_TimActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_LichSuKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_LichSuKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_LichSuKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_LichSuKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_LichSuKhachHang().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myTable_1Lan;
    private javax.swing.JTable myTable_TraGop;
    private javax.swing.JTextField txt_MaKhachHang;
    // End of variables declaration//GEN-END:variables
}
